// Article content for /ratgeber/[slug] pages.
// Each article: 1500-2200 words, H2/H3 structured, regional specifics
// (PLZ, Landkreise, Bundesnaturschutzgesetz refs) for E-E-A-T 2026.
// Markdown-like format rendered by ratgeber/[slug]/page.tsx.

export interface ArticleSection {
  type: "p" | "h2" | "h3" | "list" | "ol" | "quote" | "callout";
  text?: string;
  items?: string[];
  title?: string;
}

export const RATGEBER_CONTENT: Record<string, ArticleSection[]> = {
  // ════════════════════════════════════════════════════════════════
  "hecke-schneiden-wann-osnabrueck": [
    { type: "p", text: "Wer in Osnabrück und im umliegenden Niedersachsen oder Nordrhein-Westfalen eine Hecke pflegt, steht jährlich vor zwei Fragen: Wann darf ich überhaupt schneiden? Und wie oft sollte es sein? Beide Fragen haben präzise Antworten — eine kommt aus dem Bundesnaturschutzgesetz, die andere aus der Pflanzenphysiologie der jeweiligen Heckenart. Dieser Guide bündelt beides für die Region Osnabrücker Land, Münsterland und Ostwestfalen-Lippe." },
    { type: "h2", text: "Gesetzlicher Rahmen — was § 39 Bundesnaturschutzgesetz vorschreibt" },
    { type: "p", text: "§ 39 Abs. 5 BNatSchG verbietet zwischen dem 1. März und dem 30. September das Roden, Stockholz-Schneiden und kräftige Zurückschneiden von Hecken, Knicks, lebenden Zäunen und Gebüschen. Pflegeschnitte — also Formschnitte zum Erhalt der Heckenform — sind in dieser Zeit ausdrücklich erlaubt, sofern keine brütenden Vögel betroffen sind. Diese Regelung gilt bundesweit, also sowohl in Niedersachsen als auch in Nordrhein-Westfalen, und damit auch im gesamten Einsatzgebiet rund um Osnabrück." },
    { type: "p", text: "In der Praxis bedeutet das: Zwischen Oktober und Februar dürfen Sie eine Hecke beliebig stark zurückschneiden, auf den Stock setzen oder roden. Zwischen März und September sind nur leichte Form- und Pflegeschnitte zulässig, und auch nur dann, wenn Sie sicherstellen, dass keine Brut gestört wird. Bei Verstößen drohen je nach Bundesland Bußgelder bis 50 000 €." },
    { type: "h2", text: "Beste Schnittzeit nach Heckenart" },
    { type: "h3", text: "Liguster, Hainbuche, Buche" },
    { type: "p", text: "Diese drei Klassiker im Osnabrücker Land vertragen 2 bis 3 Schnitte pro Jahr. Empfehlung: Hauptpflegeschnitt im Juni nach dem ersten Wachstumsschub (vor Johanni am 24. Juni — daher der Begriff „Johannisschnitt“), zweiter Schnitt Ende August/Anfang September. Ein optionaler Korrekturschnitt im Oktober vor dem Winter ist möglich." },
    { type: "h3", text: "Thuja (Lebensbaum)" },
    { type: "p", text: "Beliebt in NDS/NRW als Sichtschutz. Schneidet man am besten Ende Mai und Anfang September. Wichtig: Niemals ins alte, nicht mehr begrünte Holz schneiden — Thuja treibt aus altem Holz nicht mehr aus, das verkahlte Loch bleibt dauerhaft sichtbar." },
    { type: "h3", text: "Eibe" },
    { type: "p", text: "Die Eibe ist sehr schnittverträglich und treibt sogar aus altem Holz wieder aus. 1-2 Schnitte pro Jahr — Mai und August. Für Rückschnitte ist die ruhende Phase November bis Februar ideal." },
    { type: "h3", text: "Kirschlorbeer" },
    { type: "p", text: "Ein Schnitt im Juni reicht meist. Wichtig: Mit der Astschere oder Heckenschere — Motorscheren mit feinem Messer beschädigen die großen Blätter, was unästhetisch aussieht und Pilzbefall begünstigt." },
    { type: "h3", text: "Buchsbaum" },
    { type: "p", text: "Maximal 2 Schnitte pro Jahr (April und August), nicht in praller Mittagssonne. Achtung Buchsbaumzünsler: Vor dem Schnitt prüfen — befallene Pflanzen müssen separat entsorgt werden." },
    { type: "h2", text: "Werkzeugwahl: was sich für welche Hecke eignet" },
    { type: "list", items: [
      "Hecken bis 2 m Höhe und ≤ 30 m Länge: elektrische Heckenschere mit Akku oder Kabel.",
      "Hecken über 2 m: Akku-Heckenschere mit Verlängerung oder Teleskop-Heckenschere — sicherer als Leiter.",
      "Sehr dichte oder verholzte Hecken: zuerst grobe Schnitte mit der Astschere, dann mit der Heckenschere nachformen.",
      "Großflächige Hecken (Außenanlagen, Firmenhecken): benzin- oder akkubetriebene Profi-Heckenscheren mit langer Klinge.",
    ] },
    { type: "h2", text: "Optimale Heckenform: warum trapezförmig?" },
    { type: "p", text: "Eine Hecke sollte unten breiter sein als oben — leicht trapezförmig. Der Grund ist Licht: Wenn die Oberseite mit der Zeit breiter wird als der Fuß, beschattet sie das untere Drittel der Pflanze. Dieses verkahlt dann, wird braun und treibt nicht mehr aus. Eine kahle Heckenbasis ist eines der häufigsten Probleme bei vernachlässigten Hecken im Osnabrücker Land — und mit der richtigen Form von Anfang an leicht zu vermeiden." },
    { type: "h2", text: "Was kostet Hecke schneiden lassen in Osnabrück und Umgebung?" },
    { type: "p", text: "Marktpreise in der Region (Stand 2026):" },
    { type: "list", items: [
      "Stundenlohn Heckenschnitt: 30–45 € (netto, ohne Materialkosten).",
      "Pauschal pro laufendem Meter: ca. 7–12 € bei einer Hecke bis 2 m Höhe.",
      "Pauschal pro Quadratmeter Heckenfläche (gerechnet auf die Schnittfläche): 3–6 €.",
      "Anfahrt: bei lokalen Anbietern im Umkreis Osnabrück oft enthalten oder pauschal 20–40 €.",
      "Entsorgung Schnittgut: typisch 5–10 € pro m³ oder im Stundenlohn enthalten.",
    ] },
    { type: "p", text: "Bei Rund ums Haus Littawe ist die Besichtigung kostenlos und unverbindlich — im gesamten Einsatzgebiet bis 60 km um Osnabrück. Anschließend erhalten Sie ein verbindliches Angebot, entweder zum Stunden- oder Festpreis." },
    { type: "h2", text: "Schnittgut entsorgen — Wege im Landkreis Osnabrück und Nachbarn" },
    { type: "p", text: "Im Landkreis Osnabrück können Sie Heckenschnitt bei den Awigo-Annahmestellen abgeben (z.B. Atter, Bramsche, Melle, Quakenbrück). Im Kreis Steinfurt nutzen Sie die Wertstoffhöfe der Kreisabfallwirtschaft. Wer einen Garten mit Komposterstellung hat, kann den feinen Anteil selbst kompostieren — verholzte Triebe gehören jedoch in die Grünabfall-Annahme." },
    { type: "h2", text: "Häufige Fehler beim Heckenschnitt" },
    { type: "ol", items: [
      "Zu starker Rückschnitt während der Brutzeit (1. März – 30. September) — Bußgeldgefahr.",
      "Schnitt in praller Mittagssonne — Sonnenbrand auf den frisch geschnittenen Trieben, vor allem bei Buchsbaum und Kirschlorbeer.",
      "Hecke oben breiter als unten — verkahlt mit der Zeit am Fuß.",
      "Bei Thuja oder Wacholder ins alte Holz schneiden — keine Regeneration möglich.",
      "Stumpfes Werkzeug — quetscht statt zu schneiden, was die Hecke krankheitsanfällig macht.",
    ] },
    { type: "h2", text: "Wann lohnt sich der Profi?" },
    { type: "p", text: "Bei Hecken bis 1,80 m und überschaubarer Länge (bis 20 m) ist der Eigenschnitt oft sinnvoll, wenn Werkzeug, Zeit und Sicherheit (keine Leiterarbeit ohne Sicherung) gegeben sind. Ab Höhen über 2 m, bei langen oder schwer zugänglichen Hecken oder bei Zeitknappheit lohnt sich ein professioneller Anbieter — vor allem, weil das Schnittgut gleich abtransportiert wird und kein Restmüll bei Ihnen liegen bleibt." },
    { type: "h2", text: "Werkzeug-Vergleich: welche Heckenschere für welchen Garten?" },
    { type: "h3", text: "Akku-Heckenschere (60–500 €)" },
    { type: "p", text: "Für mittlere Gärten bis 50 m Hecke das beste Allround-Werkzeug. Vorteile: leise (wichtig in Wohnvierteln in Osnabrück und Bramsche, wo Lärmschutzregelungen sonntags gelten), keine Abgase, leichter als Benziner. Nachteile: begrenzte Akkulaufzeit (typisch 30-60 min), bei sehr langen Hecken zweiter Akku nötig. Praxis-Tipp: ein Modell mit gleichem Akku-System wie der Rasenmäher kaufen — spart Geld und Aufwand bei Ersatzakkus." },
    { type: "h3", text: "Benzin-Heckenschere (300–800 €)" },
    { type: "p", text: "Für lange Hecken über 50 m oder dichte, stark verholzte Hecken sinnvoll. Vorteile: praktisch unbegrenzte Laufzeit, hohe Schnittleistung. Nachteile: laut, Wartung (Vergaser, Kerze), Abgase. In dicht bebauten Stadtgebieten in Osnabrück eher unerwünscht, in ländlicheren Lagen wie Bramsche, Melle oder im Osnabrücker Land aber praktikabel." },
    { type: "h3", text: "Teleskop-Heckenschere (200–600 €)" },
    { type: "p", text: "Mit verlängertem Stab — schneidet Hecken bis ca. 4 m Höhe ohne Leiter. Sicherheitsvorteil: Sie bleiben am Boden. Für hohe Sichtschutzhecken (Thuja, Liguster, Kirschlorbeer in einer Höhe von 2,5-3,5 m) das richtige Werkzeug. Bei dichten Hecken arbeitet es etwas langsamer als ein klassisches Modell." },
    { type: "h3", text: "Manuelle Heckenschere (15–80 €)" },
    { type: "p", text: "Für sehr kleine Hecken oder Feinarbeiten am Buchsbaum. Mehr Kontrolle, kein Strom. Bei jeder Hecke über 5 m Länge wird's anstrengend." },
    { type: "h2", text: "Heckenschnitt im Mehrfamilienhaus — wer ist verantwortlich?" },
    { type: "p", text: "Bei Mehrfamilienhäusern in Osnabrück, Bramsche und allen umliegenden Städten ist die Heckenpflege grundsätzlich Aufgabe des Eigentümers oder der Eigentümergemeinschaft. Eine Übertragung auf Mieter über Mietvertrag ist nur dann wirksam, wenn die Übertragung explizit, klar formuliert und mit Werkzeug-Stellung verknüpft ist. Faktisch übernehmen das in 90% der Fälle Hausmeisterservices oder Gartenbaubetriebe — verlässlicher und rechtssicherer als wechselnde Mieter-Verantwortlichkeiten." },
    { type: "p", text: "Praxis-Tipp für Hausverwaltungen: Bei Mehrfamilienhäusern empfehle ich einen Jahresvertrag, der mindestens 2 Heckenschnitte (Juni + August/September) enthält, plus optional einen Auswachs-Schnitt im Februar. Kosten je nach Heckenlänge — bei 30-50 m Hecke etwa 250-450 € pro Saison inklusive Schnittgut-Entsorgung. Das ist deutlich günstiger als wenn Mieter Werkzeug stellen müssten und Streit über Verantwortlichkeiten entsteht." },
    { type: "h2", text: "Häufige Folgen falscher Heckenschnitte" },
    { type: "p", text: "Werden Heckenschnitte falsch ausgeführt, leidet die Pflanze über Jahre. Hier die häufigsten Folgen, die wir in der Region Osnabrück immer wieder sehen:" },
    { type: "list", items: [
      "Verkahlung am Heckenfuß: Die Hecke wurde Jahr für Jahr nur oben geschnitten, der Fuß bekam zu wenig Licht. Sanierung: über 3-5 Jahre Auf-Stock-Schnitt im Februar (nur erlaubt vor 1. März).",
      "Krankheitsanfälligkeit durch stumpfes Werkzeug: Quetsch-Schnitte trocknen aus, Pilze finden Eintrittspforten. Fix: Klingen vor jeder Saison schärfen lassen oder selbst nachschleifen.",
      "Sonnenbrand am Buchsbaum oder Kirschlorbeer: Schnitt in praller Mittagssonne lässt die frischen Schnittflächen verbrennen. Fix: morgens oder abends schneiden, bei bewölktem Himmel optimal.",
      "Lebensraumverlust für Vögel: Schnitt während der Brutzeit (1. März – 30. September) gefährdet Bruten. Fix: vorher prüfen, ob Nester sichtbar sind, bei Verdacht 4 Wochen warten.",
      "Wachstumsschock durch zu starken Rückschnitt im Hochsommer: bei Hitze und Wassermangel kann die Hecke nicht genug Energie für Neuaustrieb mobilisieren. Fix: starke Rückschnitte nur zwischen Oktober und Februar.",
    ] },
    { type: "h2", text: "Heckenschnitt in der Region Osnabrücker Land — was zu beachten ist" },
    { type: "p", text: "Im Osnabrücker Land und im angrenzenden Münsterland herrscht ein atlantisch geprägtes Klima mit milden Wintern und feuchten Sommern. Das hat Folgen für den Heckenschnitt: Hecken wachsen hier meist kräftiger als in Süddeutschland, was häufigere Schnitte rechtfertigt. Liguster-, Hainbuche- und Buchen-Hecken können in guten Jahren bis zu 50 cm pro Jahr zulegen. Wer die Hecke nicht 2× pro Saison schneidet, hat schnell eine kahle Basis und einen wuchernden Oberteil." },
    { type: "p", text: "Konkrete Empfehlung für Osnabrück, Bramsche, Melle, Bielefeld und das gesamte Einsatzgebiet: Pflegeschnitt Mitte Juni (nach dem ersten Wachstumsschub und vor der Hauptbrutzeit-Spätphase), zweiter Pflegeschnitt Mitte August. Bei Thuja-Hecken: ein Schnitt im Mai reicht. Bei Kirschlorbeer: Juni mit Astschere statt Heckenschere — die Riesenblätter werden sonst zerfetzt und verfärben sich." },
    { type: "h2", text: "Was kostet ein Profi-Heckenschnitt versus Eigenleistung?" },
    { type: "p", text: "Eine ehrliche Rechnung an einem typischen Beispiel: Hecke 30 m × 1,80 m hoch, Liguster, in Belm bei Osnabrück. Selbst geschnitten: ca. 6 Stunden Arbeit (inklusive Auf- und Abbau, Werkzeugholen, Schnittgut zur Grünschnitt-Annahme bringen). Werkzeug-Anschaffung Akku-Heckenschere: ~250 €, Lebensdauer ca. 5 Jahre = 50 €/Jahr. Bei Stundenlohn 35 € (typischer Bürojob brutto/Stunde): 6 × 35 = 210 € + 50 € Werkzeug = 260 € pro Schnitt × 2 Schnitte = 520 €/Saison." },
    { type: "p", text: "Profi-Schnitt: Pauschal 150-220 € pro Schnitt × 2 = 300-440 €/Saison, inklusive Schnittgut-Abtransport. Profi ist also günstiger UND spart Ihnen die körperliche Arbeit. Diese Rechnung gilt für Hauseigentümer mit nicht trivialer Erwerbsbiografie. Wer Garten als Hobby liebt, hat eine andere Wertgleichung — dann ist Eigenleistung die Wahl." },
    { type: "callout", text: "Kostenlose Besichtigung: Wir kommen unverbindlich zu Ihnen — Osnabrück, Bramscher Straße bis ins gesamte 60-km-Einsatzgebiet. Tel: +49 1523 9603175 oder kontakt@rundumshaus-littawe.de." },
  ],

  // ════════════════════════════════════════════════════════════════
  "entruempelung-kosten-osnabrueck-region": [
    { type: "p", text: "Die Frage, was eine Entrümpelung kostet, ist bei keinem anderen Service so unterschiedlich beantwortet wie bei der Haushaltsauflösung. In Osnabrück und im 60-km-Umkreis variieren die Preise zwischen 300 € (kleiner Keller) und über 8 000 € (komplettes Einfamilienhaus mit Speicher und Garage). Dieser Guide erklärt, woraus sich der Preis zusammensetzt, wo Sie als Auftraggeber Einfluss haben und welche Festpreise in der Region 2026 realistisch sind." },
    { type: "h2", text: "Drei Kostenfaktoren — und wie sie zusammenspielen" },
    { type: "h3", text: "1. Volumen" },
    { type: "p", text: "Volumen wird in Kubikmetern oder Räumen gemessen. Eine 2-Zimmer-Wohnung mit normaler Möblierung liegt bei 25–40 m³ Räumgut. Ein 3-Zimmer-Haus mit Keller und Dachboden bei 60–100 m³. Der Volumenanteil bestimmt direkt Container-, Personal- und Entsorgungskosten." },
    { type: "h3", text: "2. Zugang" },
    { type: "p", text: "Erdgeschoss mit Hofzufahrt ist der günstigste Fall. Vierter Stock ohne Aufzug ist der teuerste — pro Etage steigen die Personalstunden um 20–30 %. Schmaler Treppenflur, weite Wege zum Container, Parkverbote vor dem Haus: alles erhöht den Aufwand." },
    { type: "h3", text: "3. Entsorgungskategorien" },
    { type: "p", text: "Reiner Sperrmüll ist günstig zu entsorgen. Anteile von Sondermüll (Lacke, Öle, Asbest, alte Kühlschränke vor 1990 mit FCKW), DSGVO-relevanten Bildschirmen oder Bauschutt erhöhen den Preis je Tonne deutlich. Bei einer Standard-Wohnungsauflösung im Osnabrücker Land liegt der Sondermüll-Anteil unter 5 % — bei einer Werkstatt oder einem Keller nach Modernisierung kann er 30 % betragen." },
    { type: "h2", text: "Festpreise in der Region Osnabrück 2026 — Beispielrechnungen" },
    { type: "list", items: [
      "Keller (15–25 m³, normaler Hausrat, EG-Zugang): 350–650 €.",
      "Dachboden gleicher Größe, 2. OG ohne Aufzug: 550–850 €.",
      "1-Zimmer-Wohnung (20–30 m³, Standardmöbel): 500–900 €.",
      "2-Zimmer-Wohnung (30–50 m³): 800–1 500 €.",
      "3-Zimmer-Wohnung (50–80 m³): 1 200–2 500 €.",
      "Einfamilienhaus mit Keller (80–150 m³): 2 500–5 000 €.",
      "Komplette Haushaltsauflösung mit Garten/Garage/Schuppen: 3 500–8 000 €.",
    ] },
    { type: "p", text: "Die Spanne erklärt sich durch die drei Faktoren oben. Bei Rund ums Haus Littawe erhalten Sie nach kostenloser Besichtigung einen verbindlichen Festpreis innerhalb dieser Spanne — ohne versteckte Zusatzkosten." },
    { type: "h2", text: "Was unsere Festpreise enthalten" },
    { type: "list", items: [
      "Anfahrt im gesamten 60-km-Einsatzgebiet (Osnabrück, Bramsche, Melle, Bielefeld, Münster und 94 weitere Städte).",
      "Komplette Räumung mit eigenen Mitarbeitern (keine Subunternehmer).",
      "Sortierung und Trennung der Materialien.",
      "Fachgerechte Entsorgung über zugelassene Wertstoffhöfe (Awigo, EGW, Kreis Steinfurt etc.).",
      "Besenreine Übergabe der Räume.",
      "Auf Wunsch: Schlüsselübergabe an Hausverwaltung.",
    ] },
    { type: "h2", text: "Warum Wertgegenstände bei uns nicht angerechnet werden" },
    { type: "p", text: "Viele Anbieter werben mit „Wertanrechnung“ — die Idee: Möbel oder Geräte, die noch verkäuflich sind, werden vom Festpreis abgezogen. Das klingt fair, ist in der Praxis aber oft intransparent. Was als „verkäuflich“ gilt, was tatsächlich verkauft werden konnte und was am Ende abgerechnet wird, liegt im Ermessen des Anbieters. Wir gehen einen anderen Weg: Festpreis ohne Wertanrechnung. Was Sie behalten oder selbst verkaufen möchten, klären Sie bei der Besichtigung mit uns — wir lassen es stehen. Was wir mitnehmen, ist Bestandteil unseres Festpreises. Sie wissen vorher genau, was Sie zahlen." },
    { type: "h2", text: "So können Sie den Preis selbst senken" },
    { type: "ol", items: [
      "Wertvolles vorab verkaufen (eBay Kleinanzeigen, lokale Plattformen).",
      "Bestimmte Möbel an Verschenkmärkte oder Sozialkaufhäuser abgeben (z.B. „Möbelfundgrube“ in Osnabrück).",
      "Persönliche Dokumente, Fotos, Erinnerungsstücke vor der Räumung sortieren.",
      "Sondermüll wenn möglich vorab zum Wertstoffhof bringen — reduziert die Entsorgungspauschale.",
      "Mehrere Anbieter zur Besichtigung einladen und Festpreise vergleichen.",
    ] },
    { type: "h2", text: "Was Sie unbedingt prüfen sollten" },
    { type: "list", items: [
      "Hat der Anbieter eine Betriebshaftpflicht?",
      "Werden die Mitarbeiter sozialversichert beschäftigt?",
      "Geht die Entsorgung über zertifizierte Wertstoffhöfe (kein Wildmüll)?",
      "Ist der Festpreis verbindlich oder „voraussichtlich“?",
      "Gibt es schriftliche Vertragsbestätigung mit Datum, Umfang, Preis?",
    ] },
    { type: "h2", text: "Sonderfall: Haushaltsauflösung nach Todesfall" },
    { type: "p", text: "Ein häufiger Anlass für Entrümpelungen in Osnabrück und Umgebung. Hier kommt es weniger auf den Preis als auf einfühlsames Vorgehen an: Persönliche Dokumente und Erinnerungsstücke werden gesondert übergeben, die Räumung erfolgt zeitlich abgestimmt mit Erbschein, Wohnungskündigung und Haushaltsversicherung. Wir planen das in Ruhe mit Ihnen — Termine sind in solchen Fällen oft 2–4 Wochen im Voraus, manchmal auch kurzfristig nötig." },
    { type: "h2", text: "Anfrage und Besichtigung — wie es bei uns abläuft" },
    { type: "ol", items: [
      "Anfrage per Telefon (+49 1523 9603175), E-Mail oder WhatsApp. Bilder hilfreich, aber nicht zwingend.",
      "Besichtigung vor Ort innerhalb weniger Tage — kostenlos und unverbindlich.",
      "Verbindliches Festpreisangebot, schriftlich oder per E-Mail.",
      "Nach Auftragsbestätigung: Termin innerhalb von 1–2 Wochen, bei Dringlichkeit auch kurzfristiger.",
      "Räumung mit eigenem Team, fachgerechte Entsorgung, besenreine Übergabe.",
    ] },
    { type: "h2", text: "Sondermüll und Sondertarife — wann es teurer wird" },
    { type: "p", text: "Bei Standard-Wohnungen liegt der Sondermüll-Anteil bei 2-5 % des Volumens — alte Akkus, Energiesparlampen, Lacke aus Hobbyräumen. Diese Kosten sind in unseren Festpreisen meist enthalten. Bei Werkstätten, Garagen und Kellern nach Renovierung kann der Sondermüll-Anteil auf 30 % steigen — dann werden separate Tarife fällig:" },
    { type: "list", items: [
      "Asbest-Faserzement (Eternit-Platten vor 1993): 600-1 200 € pro Tonne, separate fachgerechte Sanierung erforderlich.",
      "Kühlschränke und Klimageräte mit FCKW (Baujahr vor 1990): 50-80 € pro Gerät.",
      "Bildschirme und Fernseher (DSGVO + Schadstoffe): 30-60 € pro Gerät, Datenträger werden zerstört.",
      "Lacke, Öle, Lösungsmittel: 15-30 € pro 10-Liter-Gebinde.",
      "Bauschutt: 80-150 € pro Tonne, separate Container nötig.",
      "Reifen mit Felgen: 8-15 € pro Stück.",
      "Klaviere, Tresore, Großgeräte: 80-300 € pro Stück (wegen Spezialwerkzeug + Personalbedarf).",
    ] },
    { type: "p", text: "Wir nennen diese Sondertarife transparent in der Besichtigung. Pauschalpreise ohne Aufdeckung von Sondermüll sind ein Warnzeichen — entweder werden später Nachzahlungen fällig, oder der Anbieter entsorgt illegal." },
    { type: "h2", text: "Rechenbeispiel im Detail: Haushaltsauflösung 3-Zi-Wohnung in Bramsche" },
    { type: "p", text: "Konkrete Kalkulation für ein typisches Beispiel im Frühjahr 2026:" },
    { type: "list", items: [
      "Anfahrt aus Osnabrück (17 km): in Festpreis enthalten.",
      "Personalkosten: 3 Mitarbeiter × 10 Stunden × 35 €/h = 1 050 €.",
      "Container 10 m³: 280 €.",
      "Entsorgung Sperrmüll 6 Tonnen: 540 €.",
      "Entsorgung Schrott: -50 € (Erlös, gegengerechnet).",
      "Entsorgung E-Schrott (1 alter Kühlschrank, 1 TV): 90 €.",
      "Endreinigung 60 m² besenrein: 120 €.",
      "Festpreis komplett: ~2 030 €.",
    ] },
    { type: "p", text: "Die einzelnen Posten sehen Sie nicht auf der Rechnung — wir geben einen Festpreis ohne versteckte Aufschläge. Aber wir kalkulieren so transparent, damit Sie nachvollziehen können, was im Festpreis enthalten ist." },
    { type: "h2", text: "Steuerliche Aspekte bei Haushaltsauflösung" },
    { type: "p", text: "Bei einer normalen Haushaltsauflösung in Osnabrück sind Entrümpelungskosten **steuerlich absetzbar als haushaltsnahe Dienstleistung** nach § 35a EStG. 20 % der Lohnkosten (max. 4 000 € pro Jahr) lassen sich von der Steuerschuld abziehen. Bei einem Festpreis von 2 030 € — davon ca. 1 200 € Lohnanteil — wären das 240 € Steuerersparnis." },
    { type: "p", text: "Wichtig: Sie müssen die Rechnung per Überweisung bezahlen (keine Barzahlung), und die Rechnung muss Lohnkosten ausweisen. Wir stellen entsprechende Rechnungen aus. Bei Haushaltsauflösung nach Todesfall gelten ergänzende Regeln zur Erbschaftsteuer (siehe separater Ratgeber)." },
    { type: "h2", text: "Was unterscheidet einen Festpreis-Anbieter von Stundenlohn-Anbietern?" },
    { type: "p", text: "Stundenlohn-Anbieter wirken auf den ersten Blick günstiger (z.B. 35 €/Mann/Stunde). Bei der Endabrechnung kommen aber oft 50-100 % mehr heraus als am Telefon angekündigt — weil das Volumen unterschätzt wurde, weil Sondermüll dazukommt, weil Container teurer werden. Festpreis-Anbieter kalkulieren konservativ und verbindlich. Sie tragen das Risiko der Volumenschätzung selbst — das ist Ihr Vorteil." },
    { type: "p", text: "Bei kleinen Aufträgen (einzelner Keller, einzelnes Zimmer) kann Stundenlohn günstiger sein. Bei mittleren und großen Aufträgen (Wohnungen, Häuser, Haushaltsauflösungen) ist Festpreis fast immer die bessere Wahl — Planungssicherheit und keine Überraschungen." },
    { type: "callout", text: "Kostenlose Besichtigung im gesamten 60-km-Umkreis — von Osnabrück über Bramsche, Melle, Vechta bis Bielefeld und Münster. Tel: +49 1523 9603175. Festpreis garantiert." },
  ],

  // ════════════════════════════════════════════════════════════════
  "dachreinigung-sinnvoll-oder-geldverschwendung": [
    { type: "p", text: "Eine Dachreinigung kostet zwischen 800 € und 4 000 € — je nach Dachgröße und Verschmutzungsgrad. Das ist viel Geld. Lohnt sich die Investition wirklich, oder ist es Geldverschwendung? Die ehrliche Antwort: Es kommt auf den Zustand des Daches und Ihre Ziele an. Dieser Guide hilft Ihnen, eine sachliche Entscheidung zu treffen." },
    { type: "h2", text: "Wann eine Dachreinigung sinnvoll ist" },
    { type: "h3", text: "1. Sichtbarer Moos- und Algenbewuchs" },
    { type: "p", text: "Wenn Ihr Dach in Osnabrück, Bramsche oder Münster grün-schwarz statt rot oder grau aussieht, hat sich Moos festgesetzt. Moos ist nicht nur ein Schönheitsproblem: Es speichert Feuchtigkeit, die bei Frost in den Ziegeln expandiert und mikroskopische Risse verursacht. Über Jahre führt das zu Ziegelbruch und in der Folge zu undichten Stellen." },
    { type: "h3", text: "2. Verstopfte Dachrinnen durch heruntergewaschene Pflanzenreste" },
    { type: "p", text: "Wenn nach jedem Regen Wasser aus überlaufenden Rinnen die Fassade hinunterläuft, ist die Reinigung dringend. Fassadenschäden durch Dauerfeuchte sind teurer zu beheben als die Dachreinigung selbst." },
    { type: "h3", text: "3. Vor einer Photovoltaik-Installation" },
    { type: "p", text: "Eine PV-Anlage hat eine Lebensdauer von 25–30 Jahren. Vorher das Dach zu reinigen und ggf. zu beschichten ist sinnvoll, weil Reinigungsarbeiten unter den Modulen später aufwendig oder unmöglich sind." },
    { type: "h3", text: "4. Vor dem Hausverkauf" },
    { type: "p", text: "Ein gepflegtes Dach erhöht den optischen Wert deutlich. Bei einer Wertermittlung wirkt sich der Zustand des Daches auf die Schätzung aus." },
    { type: "h2", text: "Wann es Geldverschwendung ist" },
    { type: "list", items: [
      "Bei einem nahezu neuen Dach (jünger als 10 Jahre) ohne Mossbewuchs.",
      "Wenn das Dach in den nächsten 5 Jahren ohnehin neu eingedeckt wird — investieren Sie das Geld besser in die neue Eindeckung.",
      "Bei sehr stark beschädigten Ziegeln (Risse, fehlende Stücke) — die Reinigung kann den Schaden vergrößern. Hier ist Reparatur die Alternative.",
      "Bei Faserzementdächern mit Asbestverdacht (vor 1993 verbaut) — hier ist die Hochdruckreinigung verboten, weil Asbestfasern freigesetzt werden.",
    ] },
    { type: "h2", text: "Das Klima im nördlichen NRW und Niedersachsen" },
    { type: "p", text: "Die Region rund um Osnabrück hat mit 750–900 mm Jahresniederschlag und überdurchschnittlich vielen Regentagen ein für Moosbewuchs günstiges Klima. Besonders Nord- und Nordwestseiten von Dächern in Bramsche, Melle, Lengerich oder Münster sind betroffen. In NDS/NRW empfehlen wir daher eine Dachkontrolle alle 5 Jahre und eine Reinigung alle 8–12 Jahre — bei Lage unter Bäumen entsprechend früher." },
    { type: "h2", text: "Reinigungsverfahren im Vergleich" },
    { type: "h3", text: "Niederdruckreinigung mit klarem Wasser" },
    { type: "p", text: "Druck 30–80 bar. Schonendster Ansatz, oft ausreichend bei moderater Verschmutzung. Kein chemischer Eintrag. Empfohlen für Tonziegel und neuere Betondachsteine." },
    { type: "h3", text: "Niederdruck mit Reinigungsmittel" },
    { type: "p", text: "Bei stärkerem Moos- und Algenbewuchs. Reinigungsmittel sollte biologisch abbaubar sein und im Anschluss gründlich abgespült werden. In Wasserschutzgebieten genehmigungspflichtig — im Landkreis Osnabrück ist das z.B. im Bereich Hahnenmoor relevant." },
    { type: "h3", text: "Heißwasserverfahren" },
    { type: "p", text: "Wasser bei 80–95 °C löst organische Verschmutzungen ohne Chemie. Effektiv und umweltfreundlich, aber teurer als Niederdruck wegen höherem Energieaufwand." },
    { type: "h3", text: "Mechanische Bürstung" },
    { type: "p", text: "Mit weichen Bürsten, oft kombiniert mit Niederdruck. Schonend für die Glasur von Tonziegeln. Ungeeignet bei sehr alten oder porösen Ziegeln." },
    { type: "h2", text: "Schutzbeschichtung — sinnvoll oder Marketingtrick?" },
    { type: "p", text: "Eine Schutzbeschichtung (acryl- oder silikonbasiert) wird nach der Reinigung aufgetragen. Sie wirkt Wasser-abweisend und macht es Moos und Algen schwerer, sich neu festzusetzen. Haltbarkeit: 5–10 Jahre, abhängig von Lage und UV-Exposition." },
    { type: "p", text: "Ehrliche Bewertung: Bei einem ohnehin gut belüfteten Dach an einer sonnigen Lage in Osnabrück ist die Beschichtung verzichtbar. An einer schattigen Nordseite mit Bäumen in der Nähe — etwa in Bissendorf, Hagen am Teutoburger Wald oder Tecklenburg — kann sie das Reinigungsintervall von 5 auf 10 Jahre verlängern. Das rechnet sich, wenn Sie das Dach auch in 10 Jahren noch besitzen." },
    { type: "h2", text: "Kosten in der Region Osnabrück 2026" },
    { type: "list", items: [
      "Reine Dachreinigung Einfamilienhaus 100–150 m² Dachfläche: 800–1 800 €.",
      "Mit Beschichtung: zusätzlich 600–1 200 €.",
      "Dachrinnenreinigung separat: 100–250 €.",
      "Hubsteigerkosten bei steilen oder hohen Dächern: zusätzlich 200–400 €.",
    ] },
    { type: "h2", text: "Was Sie bei der Auftragsvergabe prüfen sollten" },
    { type: "ol", items: [
      "Wird ein Festpreis nach Besichtigung gegeben oder nur „ab“-Preise im Telefonat?",
      "Welche Sicherung kommt zum Einsatz (Anseilung, Hubsteiger, Gerüst)?",
      "Welches Reinigungsverfahren wird konkret genutzt?",
      "Wird das Schmutzwasser fachgerecht aufgefangen oder gerät es in die Regenwasserkanalisation?",
      "Hat der Anbieter eine Betriebshaftpflicht?",
      "Welche Garantie gibt es auf die Beschichtung?",
    ] },
    { type: "h2", text: "Vergleichstabelle der Reinigungsverfahren" },
    { type: "p", text: "Welches Verfahren für welches Dach? Hier die wichtigsten Faktoren:" },
    { type: "list", items: [
      "Niederdruck Wasser pur — geeignet für: nur leicht verschmutzte Tonziegel, neue Eindeckung. Kosten: günstigste Variante. Wirkung: 50-70 % Verschmutzung weg, hält 3-5 Jahre.",
      "Niederdruck mit Reinigungsmittel — geeignet für: mittlere bis starke Verschmutzung auf Ton, Beton. Kosten: mittel. Wirkung: 80-95 % weg, hält 5-7 Jahre. Reinigungsmittel muss biologisch abbaubar sein.",
      "Heißwasser 80–95 °C — geeignet für: starker Moos- und Algenbewuchs auf Ton, Beton. Kosten: höher (Energieaufwand). Wirkung: 90-95 % weg, ohne chemische Rückstände.",
      "Mechanische Bürstung — geeignet für: ältere Dächer mit empfindlicher Glasur. Kosten: hoher Personalaufwand. Wirkung: schonend, aber nur für ebene Flächen praktikabel.",
      "Hochdruck (>120 bar) — fast nie sinnvoll. Beschädigt Ziegel, dringt in Lattenkonstruktion ein. Bei Asbest-Faserzement (vor 1993) sogar verboten — gesundheitsschädlich.",
    ] },
    { type: "h2", text: "Was tun bei Schäden während oder nach der Reinigung?" },
    { type: "p", text: "Bei einem seriösen Anbieter mit Betriebshaftpflicht ist das Risiko gering. Trotzdem: Vor Beginn fotografieren Sie das Dach und besonders auffällige Stellen (alte Risse, fehlende Mörtelfugen, lose Antennen-Halterungen). So gibt es bei Schäden keinen Streit über Vor- oder Nachherzustand. Ein guter Anbieter macht das selbst — und übergibt Ihnen die Fotos." },
    { type: "p", text: "Bei tatsächlichen Schäden (gebrochener Ziegel, beschädigte Dachrinne) deckt die Betriebshaftpflicht das ab. Wichtig: Schaden sofort melden, vor Reparatur durch Sie selbst. Ein nachträglicher Streit über bereits behobene Schäden ist selten erfolgreich." },
    { type: "h2", text: "Versicherung und Haftung bei Dacharbeiten" },
    { type: "p", text: "Drei Versicherungsebenen sind bei einer Dachreinigung relevant:" },
    { type: "list", items: [
      "Wohngebäudeversicherung des Eigentümers: deckt Sturm-, Hagel-, Feuerschäden. Bei Schäden während Bauarbeiten oft eingeschränkt — der Versicherer kann dann auf den Verursacher (Reinigungsfirma) verweisen.",
      "Betriebshaftpflicht der Reinigungsfirma: deckt Schäden, die durch Mitarbeiter oder Werkzeug am Objekt entstehen. Übliche Deckungssumme 2-5 Millionen Euro. Bei seriösen Anbietern Standard.",
      "Berufsgenossenschaft / Arbeitsschutz: deckt Personenschäden der Mitarbeiter. Wichtig für Sie als Auftraggeber: arbeiten Sie nicht mit Schwarzarbeitern. Bei einem Sturz von Ihrem Dach haftet sonst gegebenenfalls der Auftraggeber!",
    ] },
    { type: "p", text: "Praxis-Tipp: Lassen Sie sich vor Auftragserteilung den Versicherungsnachweis (Versicherungsschein-Kopie) zeigen. Das ist kein Misstrauen — das ist solide Vorsicht und für seriöse Anbieter selbstverständlich." },
    { type: "h2", text: "Wann lohnt sich Eigenleistung beim Dach NICHT?" },
    { type: "p", text: "Eigenleistung am Dach ist riskant. Hier die häufigsten Fehler, die Eigentümer in Osnabrück und Umgebung machen:" },
    { type: "list", items: [
      "Hochdruckreinigung mit Mietgeräten: zerstört die Glasur der Ziegel, verkürzt die Dach-Lebensdauer um 30-50 %.",
      "Ohne Anseilung auf dem Dach: Sturzgefahr. Allein 2025 ca. 850 schwere Unfälle bei Privatpersonen auf Dächern in Deutschland.",
      "Nicht erkanntes Asbest in Faserzement vor 1993: gesundheitsschädlich, illegale Selbstsanierung droht Bußgeld.",
      "Schmutzwasser in den Garten oder Regenwasserkanalisation laufen lassen: in den meisten Gemeinden im Landkreis Osnabrück und im Münsterland verboten, Bußgeld bis 5 000 €.",
    ] },
    { type: "p", text: "Wenn Sie überhaupt selbst arbeiten, dann nur auf Flachdächern bis 5° Neigung mit Sicherung — und mit Auffangmöglichkeit für Schmutzwasser. Alles andere ist Profi-Aufgabe." },
    { type: "callout", text: "Wir besichtigen Ihr Dach kostenlos im 60-km-Umkreis um Osnabrück und nennen Ihnen einen verbindlichen Festpreis. Telefon: +49 1523 9603175." },
  ],

  // ════════════════════════════════════════════════════════════════
  "hausmeisterservice-mehrfamilienhaus-leistungen": [
    { type: "p", text: "Wer als Vermieter, Eigentümergemeinschaft oder Hausverwaltung in Osnabrück, Bramsche oder einer der 96 weiteren Städte unseres Einsatzgebiets ein Mehrfamilienhaus betreut, kennt das Aufgabenspektrum: Treppenhausreinigung, Pflege der Außenanlagen, Müllmanagement, Kleinreparaturen, Winterdienst. Ein professioneller Hausmeisterservice bündelt all das in einer Hand. Dieser Guide zeigt, was im Standard enthalten ist, wo der Mehrwert liegt und worauf Sie bei der Vertragsgestaltung achten sollten." },
    { type: "h2", text: "Standardleistungen eines Hausmeisterservice für Mehrfamilienhäuser" },
    { type: "h3", text: "Treppenhausreinigung" },
    { type: "p", text: "Wöchentlich oder zweiwöchentlich, abhängig von Bewohnerdichte und vereinbarten Intervallen. Eingeschlossen sind: feucht wischen aller Stufen und Podeste, Geländer abwischen, Wandflecken entfernen, Eingangsbereich reinigen, Fußmatten ausklopfen, Briefkastenanlage abwischen, Spinnweben entfernen. Bei größeren Häusern auch Fenster im Treppenhaus 2-4× pro Jahr." },
    { type: "h3", text: "Pflege der Außenanlagen" },
    { type: "p", text: "Rasenmähen in der Hauptsaison (April–Oktober) wöchentlich oder zweiwöchentlich, Heckenschnitt 1-2× pro Jahr, Beetpflege, Wegekehren, Laubentfernung im Herbst. Bei Häusern mit Kinderspielplatz: Kontrolle der Sicherheit, Sandwechsel im Sandkasten." },
    { type: "h3", text: "Müllmanagement" },
    { type: "p", text: "Tonnen rausstellen am Vorabend der Abholung, am Tag der Abholung zurückstellen, Müllplatz reinigen (mindestens monatlich, bei größeren Häusern wöchentlich), Sperrmüll-Termin organisieren. Bei wiederholt falsch befüllten Tonnen: Hinweise an die Bewohner." },
    { type: "h3", text: "Kleinreparaturen" },
    { type: "p", text: "Lampenwechsel im Treppenhaus, Sicherungswechsel, Türen justieren, Schlösser ölen, kleine Sanitärarbeiten (Siphon, Wasserhahn-Dichtung), Briefkastenschlösser. Größere Reparaturen werden gemeldet und nach Auftragsbestätigung ausgeführt." },
    { type: "h3", text: "Winterdienst" },
    { type: "p", text: "November bis März: werktags vor 7:00 Uhr und sonntags vor 9:00 Uhr räumen und streuen — gemäß örtlicher Streupflicht. Bei mehrfachem Schneefall am Tag wird mehrfach gestreut. Streumittel werden gestellt oder vom Eigentümer beigestellt." },
    { type: "h3", text: "Kontrollgänge" },
    { type: "p", text: "Wöchentlicher oder monatlicher Rundgang: Heizungsraum prüfen, Keller und Dachboden auf Schäden kontrollieren, Lichter und Notbeleuchtung testen, Brandschutztüren prüfen, Außenanlagen auf Vandalismus oder Beschädigungen sichten. Tätigkeitsnachweise werden dokumentiert." },
    { type: "h2", text: "Optionale Zusatzleistungen" },
    { type: "list", items: [
      "Pflege von Aufzügen (oberflächlich, ohne Wartungsvertrag).",
      "Schädlingsbekämpfung (Wespen, Ratten in Müllräumen) — oft in Kooperation mit Spezialisten.",
      "Wohnungsabnahmen bei Mieterwechsel.",
      "Schlüsselverwaltung (Notschlüssel zentral hinterlegt).",
      "Kommunikation mit Bewohnern bei Reparaturwünschen oder Beschwerden.",
      "Gartenneuanlage, Rasensanierung — gegen separate Berechnung.",
    ] },
    { type: "h2", text: "Vertragsmodelle" },
    { type: "h3", text: "Stundenbasiert" },
    { type: "p", text: "Klassisches Modell für kleine Häuser oder unregelmäßige Aufgaben. Stundenlohn 30–45 €, monatliche Übersicht der Leistungen. Vorteil: nur bezahlt was wirklich anfällt. Nachteil: schwer kalkulierbar." },
    { type: "h3", text: "Pauschal pro Monat" },
    { type: "p", text: "Festes Leistungspaket gegen einen monatlichen Festpreis. Üblich bei Mehrfamilienhäusern ab 6 Wohneinheiten. Vorteil: planbar. Nachteil: Sonderaufgaben werden separat berechnet." },
    { type: "h3", text: "Kombinationsmodell" },
    { type: "p", text: "Pauschal für Standard (Treppe, Müll, Außen) + Stundenlohn für Reparaturen und Sondereinsätze. Häufigste Variante für Häuser mit 4–12 Einheiten." },
    { type: "h2", text: "Kosten in der Region Osnabrück 2026" },
    { type: "list", items: [
      "Mehrfamilienhaus 4–6 Wohneinheiten, Pauschalvertrag (Treppe wöchentlich, Außen monatlich, Müll, Winterdienst): 250–450 € / Monat.",
      "8–12 Wohneinheiten: 450–800 € / Monat.",
      "Größere Wohnanlage 20+ Wohneinheiten: ab 1 200 € / Monat, individuelle Kalkulation.",
      "Stundenlohn für Sonderaufgaben: 30–45 €.",
      "Winterdienst-Pauschale für Saison Nov–März: 150–500 € je nach Fläche.",
    ] },
    { type: "h2", text: "Worauf bei der Auswahl achten" },
    { type: "ol", items: [
      "Schriftlicher Vertrag mit klar definierten Leistungen, Intervallen, Festpreis und Sonderaufgaben-Tarif.",
      "Dokumentationspflicht: monatliche Berichte über erledigte Leistungen.",
      "Festen Ansprechpartner — kein wechselndes Team.",
      "Nachweis Betriebshaftpflicht.",
      "Sozialversicherte Mitarbeiter (kein Schwarzarbeit-Risiko für Sie als Auftraggeber).",
      "Reaktionszeit bei Notfällen vereinbart (z.B. Heizungsausfall am Wochenende).",
      "Kündigungsfrist fair geregelt (üblich: 1-3 Monate).",
    ] },
    { type: "h2", text: "Wer trägt welche Pflichten? Vermieter vs. Hausmeisterservice" },
    { type: "p", text: "Wichtig: Auch wenn Sie einen Hausmeisterservice beauftragen, bleibt der Eigentümer letztverantwortlich für Verkehrssicherungspflichten (Streupflicht, Treppenhaussicherheit, Brandschutz). Der Service ist ausführendes Organ — Sie als Eigentümer prüfen die Einhaltung. Eine gute Vertragsklausel: regelmäßige Kontrolle (monatlich) durch den Eigentümer mit dokumentierter Begehung." },
    { type: "h2", text: "Vertragsbeispiele aus der Praxis" },
    { type: "h3", text: "Beispiel 1: 6-Familienhaus in Osnabrück, Eversburg" },
    { type: "p", text: "Mietshaus aus den 1970er-Jahren, mittlere Lage, Bewohnerstruktur gemischt. Vereinbarung: Treppenhausreinigung wöchentlich (Donnerstag), Außenanlage 14-tägig in der Saison, Müllplatz wöchentlich, Winterdienst Saison-Pauschale, Kleinreparaturen nach Stunden. Kosten ca. 380 € im Monat. Vorteil: ein Ansprechpartner für Mieter (per WhatsApp-Nummer), monatliche Übersicht, Jahresvertrag mit 3 Monaten Kündigungsfrist." },
    { type: "h3", text: "Beispiel 2: 12-Wohneinheiten in Bielefeld-Mitte" },
    { type: "p", text: "Modernes Mehrfamilienhaus, 2010 gebaut, Eigentümergemeinschaft. Vereinbarung: vollumfänglicher Hausmeisterservice mit Treppenhaus (2× pro Woche), Außenanlage wöchentlich, Müll, Winterdienst, Kleinreparaturen pauschal bis 30 Min/Monat enthalten. Kosten ca. 720 € im Monat. Bei Sondereinsätzen: Stundenlohn 38 € netto." },
    { type: "h3", text: "Beispiel 3: Wohnpark mit 24 Einheiten in Melle" },
    { type: "p", text: "Wohnanlage mit zwei Häusern, gemeinsame Außenanlagen, Tiefgarage. Vereinbarung: täglicher Kontrollgang im Winter, wöchentlich im Sommer, Reinigung der Tiefgaragenzufahrt monatlich, Pflege Spielplatz inkl. Sicherheitsprüfung. Kosten ca. 1 200 € im Monat. Voller Tätigkeitsnachweis monatlich als PDF." },
    { type: "h2", text: "Hausordnung und Hausmeister-Pflichten — wo liegt die Grenze?" },
    { type: "p", text: "Der Hausmeister ist nicht für die Hausordnung verantwortlich. Wenn Mieter im Treppenhaus Müll lagern, falsche Tonnen befüllen oder Fahrräder im Eingangsbereich abstellen, ist es Aufgabe der Hausverwaltung, das zu adressieren — nicht des Hausmeisters. Wir dokumentieren solche Vorkommnisse aber gerne im monatlichen Tätigkeitsnachweis und melden Auffälligkeiten zeitnah. So hat die Hausverwaltung eine objektive Grundlage für ein Mahnschreiben oder Gespräch." },
    { type: "p", text: "Auch nicht zu unseren Aufgaben gehören: Schlichtung von Mieter-Streitigkeiten, Lärmprobleme zwischen Bewohnern, Reparaturen innerhalb der Wohnungen (das ist Sache des Mieters bzw. der Versicherung), Schädlingsbekämpfung mit Spezialgeräten. Bei diesen Themen vermitteln wir gerne lokale Fachbetriebe aus unserem Netzwerk im Landkreis." },
    { type: "h2", text: "Hausmeisterservice beim Mieterwechsel" },
    { type: "p", text: "Bei einem Mieterwechsel kann der Hausmeisterservice deutlich entlasten. Typische Aufgaben:" },
    { type: "list", items: [
      "Wohnungsabnahme mit Übergabeprotokoll, Foto-Dokumentation und Zählerstand-Aufnahme.",
      "Schlüsselübergabe und -annahme (mit Quittung).",
      "Kontrolle auf Schäden gemäß Mietvertrag.",
      "Kleine Renovierungsarbeiten zwischen Mietverhältnissen: Wände streichen, Bohrlöcher schließen, Türen justieren, Silikonfugen erneuern.",
      "Reinigung der Wohnung (besenrein) für die nächste Übergabe.",
      "Wohnungsübergabe an den neuen Mieter mit Einweisung in Heizung, Klingel, Brieftaste.",
    ] },
    { type: "p", text: "Diese Leistungen rechnen wir transparent nach Stunden oder Festpreis ab — je nach Wunsch der Hausverwaltung. Pauschale für eine Standard-Wohnungsübergabe (60 m², ohne Renovierung): 80-150 €. Mit kleiner Renovierung: 250-500 €." },
    { type: "h2", text: "Wann lohnt sich ein zusätzlicher Concierge-Service?" },
    { type: "p", text: "Bei Wohnanlagen ab 20 Wohneinheiten und gehobenem Standard kann ein Concierge-Service über die normale Hausmeisterfunktion hinaus wertvoll sein: Paketannahme, Mieter-Kommunikation, kleine Service-Aufgaben für Bewohner. In Osnabrück und Umgebung gibt es wenige Anbieter, die das in Kombination mit Hausmeisterservice leisten — bei Bedarf gerne ansprechen." },
    { type: "callout", text: "Sie betreuen ein Mehrfamilienhaus in Osnabrück, Bramsche, Bielefeld oder Umgebung? Wir kommen zur kostenlosen Besichtigung und kalkulieren Ihnen ein passendes Modell. +49 1523 9603175." },
  ],

  // ════════════════════════════════════════════════════════════════
  "kostenlose-schrottabholung-wie-funktioniert": [
    { type: "p", text: "„Kostenlose Schrottabholung“ klingt zu gut, um wahr zu sein — und genau deshalb sind viele Kunden skeptisch. Tatsächlich funktioniert das Modell wirtschaftlich, weil Altmetall einen Materialwert hat, der die Anfahrt und den Aufwand für den Anbieter abdeckt. Dieser Guide erklärt, wie es genau läuft, was abgeholt wird, was nicht, und worauf Sie achten sollten." },
    { type: "h2", text: "Warum ist es kostenlos?" },
    { type: "p", text: "Altmetall (Eisen, Aluminium, Kupfer, Messing) wird in Recyclinganlagen aufbereitet und an die Stahl- und NE-Metallindustrie verkauft. Die Marktpreise variieren, lagen 2026 für Mischschrott bei 100–250 € pro Tonne, für Kupfer bei 6 000–8 500 € pro Tonne. Selbst bei einer haushaltsüblichen Menge von 100–300 kg pro Abholung ergibt sich ein Erlös, der die Anfahrt und Personalkosten kompensiert — daher kann der Service für Sie kostenfrei angeboten werden." },
    { type: "h2", text: "Was wird in der Region Osnabrück abgeholt?" },
    { type: "list", items: [
      "Heizkörper (Eisen, Stahl).",
      "Wasser- und Heizungsrohre (Kupfer, Eisen, verzinkt).",
      "Alte Werkzeuge aus Metall.",
      "Stromkabel (Kupferkern wird durch Hammermühle aufbereitet).",
      "Alte Gartengeräte (Spaten, Hacken, Rasenmäher mit Metallgehäuse).",
      "Stahlträger, Bleche, Geländer.",
      "Maschinenteile (Pumpen, Motoren ohne Öl).",
      "Schrottautoteile (Felgen, Auspuff, Stoßstangen — keine kompletten Karosserien).",
      "Alte Räder mit Metallrahmen (Felgen, Lenker).",
      "Metallzäune, Tore.",
    ] },
    { type: "h2", text: "Was wird NICHT mitgenommen?" },
    { type: "list", items: [
      "Bauschutt (Beton, Ziegel) — gehört in den Wertstoffhof, kostenpflichtig.",
      "Restmüll und Hausmüll.",
      "Holz — separate Holzentsorgung über die kommunale Annahme.",
      "Elektrogeräte mit Bildschirm (TV, Monitore, PCs) — DSGVO-relevant, müssen über zertifizierte E-Schrott-Annahmen.",
      "Akkus und Batterien — Sondermüll, separat.",
      "Schadstoffe: Öl, Lack, Asbest, Asbestzement.",
      "Kühlschränke und Klimageräte mit FCKW (Baujahr vor 1990) — Sondermüll.",
    ] },
    { type: "p", text: "Im Landkreis Osnabrück gehen diese Materialien zu den Wertstoffhöfen der Awigo, im Kreis Steinfurt zu den Wertstoffsammelstellen, im Kreis Vechta zur AWV. Bauschutt wird privat über zugelassene Container-Dienste entsorgt." },
    { type: "h2", text: "Ablauf der Abholung Schritt für Schritt" },
    { type: "ol", items: [
      "Anfrage per Telefon oder WhatsApp. Foto des Schrotthaufens hilft bei der Vorabschätzung.",
      "Termin innerhalb weniger Werktage (im 60-km-Umkreis um Osnabrück).",
      "Schrott wird vorab gut zugänglich gemacht — vor dem Haus, in der Einfahrt oder im Garten.",
      "Wir kommen mit Transporter oder Anhänger, je nach Menge.",
      "Kurze Übergabe vor Ort, ggf. auch ohne Anwesenheit nach Absprache.",
      "Schrott wird verwogen und im zertifizierten Recyclingbetrieb aufbereitet.",
    ] },
    { type: "h2", text: "Bekomme ich Geld für den Schrott?" },
    { type: "p", text: "Bei haushaltsüblichen Mengen ist die Abholung kostenlos — ohne Auszahlung. Bei sehr großen, sortenreinen Mengen (mehrere Tonnen Eisenschrott, größere Kupferbestände) sprechen Sie uns gerne an: Hier kann eine Vergütung verhandelt werden. Für die Bewertung ist die Sortenreinheit entscheidend — Mischschrott bringt einen niedrigeren Erlös als reiner Kupfer- oder Aluminiumschrott." },
    { type: "h2", text: "Vorsicht vor unseriösen Anbietern" },
    { type: "list", items: [
      "Klingelt jemand unangemeldet und bietet „kostenlose Abholung“ an — fragen Sie nach Gewerbeanmeldung und Anschrift. Ohne diese: ablehnen.",
      "Wer auf eigene Faust auf Ihrem Grundstück Schrott einsammelt ohne Berechtigung, begeht Hausfriedensbruch.",
      "Wer Geräte mit personenbezogenen Daten mitnimmt (PCs, Smartphones) — Sie tragen das Datenschutzrisiko.",
      "Anbieter ohne festen Standort, nur Mobilnummer, kein Impressum — Vorsicht.",
    ] },
    { type: "h2", text: "Anfahrtsgebiet und Termine" },
    { type: "p", text: "Wir holen Altmetall im 60-km-Umkreis um Osnabrück ab — von Münster, Bielefeld und Vechta bis Cloppenburg und Nordhorn. Termine sind in Tier 1 (≤25 km) meist binnen 2-3 Werktagen, in Tier 2 (25-45 km) 3-7 Werktagen, in Tier 3 (45-60+ km) 7-14 Werktagen möglich — wir bündeln Aufträge in entfernteren Regionen, was die Planung effizienter macht." },
    { type: "h2", text: "Unterschied Schrottabholung vs. Sperrmüll" },
    { type: "p", text: "Diese Begriffe werden oft verwechselt. Sperrmüll wird von der kommunalen Abfallwirtschaft (Awigo, EGW etc.) regelmäßig oder auf Anmeldung kostenlos abgeholt — enthält aber alle Materialien gemischt: Möbel, Geräte, Holz, Metall. Schrottabholung dagegen nimmt nur reines Altmetall mit, wird privat vom Recycler organisiert, ist nicht an einen Sperrmüll-Termin gebunden und kann viel kurzfristiger erfolgen." },
    { type: "p", text: "Praxis-Tipp für Eigentümer in Osnabrück und Umgebung: Bei Wohnungsauflösung sortieren Sie das Altmetall vorab und lassen es separat abholen. Spart Volumen beim Sperrmüll, beschleunigt die Auflösung und schont das kommunale Volumen-Kontingent (in vielen Städten begrenzt auf 3-5 m³ pro Sperrmüll-Abruf)." },
    { type: "h2", text: "Recyclingkette — was passiert mit Ihrem Schrott?" },
    { type: "p", text: "Nach der Abholung in Ihrem Garten in Osnabrück, Bramsche oder Münster geht das Altmetall einen klaren Weg:" },
    { type: "ol", items: [
      "Wertstoffhof oder Recyclingbetrieb: Verwiegung und Erstsortierung. Wir liefern bei zertifizierten Annahmestellen in der Region an.",
      "Magnetische Trennung: Eisen wird per starkem Elektromagnet vom Buntmetall (Kupfer, Aluminium, Messing) getrennt.",
      "Feinsortierung: Buntmetall wird optisch und mit Wirbelstromtechnik in Sortenreinheit getrennt — Kupfer, Aluminium, Messing einzeln.",
      "Zerkleinerung in Shredderanlagen: große Stücke werden auf einheitliche Größe gebracht.",
      "Verkauf an Stahlwerke (Eisen) und NE-Metall-Schmelzhütten (Buntmetall) — meist innerhalb Deutschlands.",
      "Wiedereinsatz: Aus Eisenschrott wird neuer Stahl, aus Kupferschrott wieder Kupfer-Halbzeug. Recyclingrate 90 %+ in Deutschland.",
    ] },
    { type: "p", text: "Diese Recyclingkette ist der Grund, warum Schrottabholung in Deutschland kostenlos funktioniert. Der Materialwert deckt unsere Kosten — ökologisch und wirtschaftlich ein gutes Modell." },
    { type: "callout", text: "Schrottabholung im 60-km-Umkreis um Osnabrück — kostenlos. Tel: +49 1523 9603175 oder kontakt@rundumshaus-littawe.de." },
  ],

  // ════════════════════════════════════════════════════════════════
  "gartenpflege-fruehjahr-checkliste": [
    { type: "p", text: "Im März und April erwacht der Garten in Osnabrück und im umliegenden NDS/NRW zu neuem Leben. Gut gepflegt im Frühjahr, läuft das Gartenjahr fast von selbst. Vernachlässigt im Frühjahr, holen Sie das in Sommer und Herbst kaum wieder auf. Diese Checkliste fasst die wichtigsten Frühjahrsarbeiten in der Region zusammen — angepasst an das Klima Niedersachsens und Nordrhein-Westfalens." },
    { type: "h2", text: "März — Vorbereitung und erste Schnitte" },
    { type: "list", items: [
      "Werkzeug warten: Heckenschere, Rasenmäher, Astscheren prüfen, schärfen, ölen.",
      "Bäume zurückschneiden (Obstbäume: Februar/März bei frostfreier Witterung).",
      "Hecken-Pflegeschnitt vor 1. März (Bundesnaturschutzgesetz: stärkere Schnitte nach 28. Februar nicht mehr erlaubt).",
      "Kompost auf Beete verteilen.",
      "Stauden zurückschneiden, abgestorbenes Laub entfernen.",
      "Frostschutz von Rosen und empfindlichen Pflanzen vorsichtig entfernen.",
    ] },
    { type: "h2", text: "April — Rasenpflege und Beetbestellung" },
    { type: "h3", text: "Vertikutieren" },
    { type: "p", text: "Bei trockenem Boden im April. Vorgehensweise: Rasen auf 2-3 cm mähen, dann mit Vertikutierer in zwei Richtungen über die Fläche fahren — Längs und Quer. Aufgenommene Filz- und Moosbestände abrechen und entsorgen. Anschließend kann der Rasen besser atmen, Wasser und Nährstoffe erreichen die Wurzel direkt." },
    { type: "h3", text: "Erste Düngung" },
    { type: "p", text: "Nach dem Vertikutieren Langzeit-Rasendünger auftragen (Frühjahrsdünger mit höherem Stickstoff-Anteil). Menge nach Herstellerangabe — meist 30 g/m². Bei Trockenheit nachwässern. Eine zweite Düngung folgt im August/September mit kalium-betontem Herbstdünger." },
    { type: "h3", text: "Nachsaat" },
    { type: "p", text: "Lückige Stellen mit Rasensaatgut ausbessern. Boden lockern, Saatgut einbringen, leicht andrücken, in den ersten 2 Wochen feucht halten. Ideal: Mitte April–Anfang Mai." },
    { type: "h3", text: "Beete vorbereiten" },
    { type: "p", text: "Boden mit der Grabegabel lockern, Kompost einarbeiten (4-6 cm Schicht). Stauden teilen und umsetzen, wenn nötig. Saisonpflanzen (Stiefmütterchen, Vergissmeinnicht, Bellis) ab Mitte April pflanzen — frostsensible Sommerblumen erst nach den Eisheiligen (15. Mai)." },
    { type: "h2", text: "Mai — Vollbetrieb" },
    { type: "list", items: [
      "Erste Mähsaison: Rasen ab 8-10 cm Höhe mähen, 4-5 cm Schnitthöhe.",
      "Hecken-Formschnitt im Mai möglich (Pflegeschnitt, kein Rückschnitt).",
      "Sommerblumen pflanzen nach den Eisheiligen.",
      "Bewässerungssystem prüfen, Tropfschläuche, Sprinkler einstellen.",
      "Gartenmöbel und Geräte zur Saison aufstellen.",
    ] },
    { type: "h2", text: "Region-spezifische Hinweise für Osnabrücker Land und Münsterland" },
    { type: "p", text: "Das Klima im nördlichen NRW und südlichen Niedersachsen ist atlantisch geprägt: milde Winter, eher feuchte Sommer, Niederschläge gleichmäßig über das Jahr verteilt. Daraus ergeben sich Konsequenzen für die Frühjahrspflege:" },
    { type: "list", items: [
      "Mossbildung im Rasen ist überdurchschnittlich häufig — Vertikutieren ist hier wichtiger als in trockeneren Regionen.",
      "Pilzkrankheiten (Schneeschimmel, Roter Faden) treten häufiger auf — Rasenpflege mit guter Entwässerung wichtig.",
      "Kirschlorbeer- und Buchsbaumzünsler sind in NDS/NRW etabliert — Frühjahrskontrolle wichtig.",
      "Frühe Mähsaison: ab Ende März/Anfang April, 4–6 Wochen früher als in Süddeutschland.",
    ] },
    { type: "h2", text: "Werkzeug-Checkliste" },
    { type: "ol", items: [
      "Rasenmäher: Messer schärfen, Ölwechsel beim Benziner.",
      "Vertikutierer: Messer und Federn prüfen.",
      "Heckenschere: Schneidemesser ölen, schärfen.",
      "Astschere und Astsäge: Klingen schärfen.",
      "Spaten und Hacke: Stiele kontrollieren.",
      "Gartenschlauch: auf Risse prüfen, Anschlüsse erneuern.",
      "Akkus: aufladen, defekte ersetzen.",
    ] },
    { type: "h2", text: "Wann sich der Profi lohnt" },
    { type: "p", text: "Bei kleinen Stadtgärten in Osnabrück (bis 200 m²) ist die Frühjahrspflege gut alleine zu schaffen. Ab 500 m² Gartenfläche oder bei langen Hecken (>30 m) lohnt sich eine professionelle Unterstützung — vor allem für die zeitkritischen Arbeiten Vertikutieren, Hecken-Pflegeschnitt und Düngung. Wir bieten in der Region Osnabrück sowohl einmalige Frühjahrspflege-Pakete als auch ganzjährige Betreuungsverträge mit dokumentiertem Pflegeplan." },
    { type: "h2", text: "Bodenanalyse selber machen" },
    { type: "p", text: "Bevor Sie düngen, sollten Sie wissen, was Ihr Boden eigentlich braucht. Eine einfache Selbst-Analyse:" },
    { type: "ol", items: [
      "pH-Wert messen: pH-Teststreifen aus dem Baumarkt (5-15 €). Optimaler Rasen-pH: 5,5-6,5. Im Osnabrücker Land oft saurer (Moor- und Sandböden), kalken sinnvoll.",
      "Bodentextur prüfen: eine Handvoll Erde anfeuchten, formen. Bröselt es: sandig (Wasser läuft schnell durch, magert aus). Klebt: lehmig (speichert Nährstoffe, neigt zu Verdichtung). Mittelweg: Lehm-Sand-Gemisch — ideal.",
      "Verdichtung testen: Spaten in den Boden stechen. Geht er bei mittlerer Kraft 25 cm tief: ok. Stoppt er nach 10 cm: verdichtet, Aerifizieren nötig.",
      "Mossanteil im Rasen schätzen: bei >20 % grünem Moss pro m²: Vertikutieren dringend nötig.",
    ] },
    { type: "p", text: "Mit diesen 4 einfachen Tests entscheiden Sie, ob Sie düngen, kalken, vertikutieren oder aerifizieren müssen. Bei Profi-Arbeit machen wir diese Tests in der Besichtigung." },
    { type: "h2", text: "Pflanzen für trockene oder schattige Standorte in der Region Osnabrück" },
    { type: "p", text: "Nicht jeder Garten in Osnabrück oder Bramsche hat die idealen Bedingungen. Hier robuste Pflanzen, die mit schwierigen Standorten gut zurechtkommen:" },
    { type: "list", items: [
      "Trockenstandort (Süd-Lage, sandiger Boden): Lavendel, Salbei, Thymian, Schafgarbe, Ziergräser (Pennisetum), Mauerpfeffer, Steinrose. Wenig Pflege, lange Blüte.",
      "Schattenstandort (Nord-Lage, unter Bäumen): Funkien (Hosta), Farne, Storchschnabel, Schaumblüte, Walderdbeere, Astilbe. Funkien sind im Osnabrücker Land sehr beliebt — robust gegen Schnecken (sortenabhängig).",
      "Halbschatten mit feuchtem Boden: Hortensien, Astilben, Bergenien, Funkien, Tränendes Herz. Ideal für Reihenhaus-Gärten in der Stadt.",
      "Bienen- und Insektenfreundlich: einheimische Wildstauden bevorzugen — Wiesensalbei, Margerite, Glockenblume, Wilde Karde. In NDS und NRW gibt es Förderungen für insektenfreundliche Vorgärten.",
    ] },
    { type: "h2", text: "Bewässerungsplan Frühling-Sommer" },
    { type: "p", text: "In der Hauptsaison (Mai-September) braucht ein Garten in Osnabrück bei normalem Wetter etwa 25-30 mm Niederschlag pro Woche — das entspricht 25-30 Liter Wasser pro Quadratmeter. Bei längerer Trockenheit müssen Sie ergänzen. Wann gießen?" },
    { type: "list", items: [
      "Rasen: nur bei sichtbarer Trockenheit (Tritt-Spuren bleiben). Dann gründlich (20-25 mm), damit das Wasser tief eindringt — fördert tiefe Wurzeln. Lieber 1× pro Woche viel als täglich wenig.",
      "Beete: morgens oder abends, nicht in der Mittagssonne (Verdunstung + Sonnenbrand). Stauden brauchen weniger als Sommerblumen.",
      "Hecken: jung gepflanzte Hecken die ersten 2 Jahre intensiv gießen. Etablierte Hecken nur bei extremer Trockenheit.",
      "Topfpflanzen auf Terrasse: bei Hitze täglich. Selbstbewässernde Töpfe oder Tropfschlauch sparen viel Zeit.",
    ] },
    { type: "p", text: "Faustregel: Regenwasser aus Tonnen ist besser als Leitungswasser (kein Kalk, Pflanzen mögen es). In den meisten Häusern in Osnabrück und Umgebung passen 1-2 große Regentonnen problemlos hinter den Schuppen." },
    { type: "callout", text: "Frühjahrspflege im 60-km-Umkreis um Osnabrück — kostenlose Besichtigung. Tel: +49 1523 9603175." },
  ],

  // ════════════════════════════════════════════════════════════════
  "haushaltsaufloesung-todesfall-was-beachten": [
    { type: "p", text: "Eine Haushaltsauflösung nach einem Todesfall ist mehr als eine Räumung — sie ist ein Akt zwischen Trauer, Verantwortung und administrativer Abwicklung. Wer im Osnabrücker Land, Münsterland oder Ostwestfalen für einen verstorbenen Angehörigen die Wohnung auflösen muss, steht vor rechtlichen, finanziellen und emotionalen Fragen. Dieser Guide hilft, den Überblick zu behalten." },
    { type: "h2", text: "Schritt 1 — die ersten Tage" },
    { type: "p", text: "Unmittelbar nach dem Todesfall geht es nicht um die Räumung. In den ersten 1–2 Wochen organisieren Sie Bestattung, Sterbeurkunde (mehrere Ausfertigungen, Sie brauchen sie überall) und melden den Tod den wichtigsten Stellen: Krankenkasse, Rentenversicherung, Bank, Versicherungen, Vermieter. Erst nach dieser ersten Welle macht es Sinn, sich der Wohnung zu widmen." },
    { type: "h2", text: "Schritt 2 — Erbenstellung klären" },
    { type: "p", text: "Bevor Sie Wertgegenstände verteilen oder die Wohnung räumen, sollten Sie sicher sein, dass Sie als Erbe handlungsberechtigt sind. Bei einem Testament: Eröffnung beim Nachlassgericht (in Osnabrück: Amtsgericht Osnabrück, Kollegienwall 7). Ohne Testament gilt die gesetzliche Erbfolge, dann benötigen Sie meist einen Erbschein (kostenpflichtig, Höhe abhängig vom Nachlasswert)." },
    { type: "p", text: "Wichtig: Ohne klare Erbenstellung kann jede Räumung später als unbefugte Verfügung gewertet werden. Wenn mehrere Erben existieren, sollten alle der Räumung schriftlich zustimmen — am besten formlos schriftlich oder per E-Mail." },
    { type: "h2", text: "Schritt 3 — Wohnung kündigen oder verkaufen" },
    { type: "p", text: "Bei Mietwohnungen: Sonderkündigungsrecht der Erben (§ 564 BGB). Sie können binnen 1 Monat nach Kenntnis des Erbfalls mit einer 3-Monatsfrist kündigen — auch ohne Vorlage eines Erbscheins. Vermieter erhalten oft eine eidesstattliche Versicherung als Übergangslösung." },
    { type: "p", text: "Bei Eigentumswohnungen oder Häusern: Verkauf erfordert Erbschein. Der Termin der Räumung sollte mit dem geplanten Übergabedatum abgestimmt sein." },
    { type: "h2", text: "Schritt 4 — Wertvolles und Persönliches sortieren" },
    { type: "p", text: "Gehen Sie nach Möglichkeit selbst durch die Wohnung, bevor ein Entrümpler kommt. Sortieren Sie:" },
    { type: "list", items: [
      "Persönliche Dokumente: Ausweis, Testament, Sparbücher, Versicherungspolicen, Mietverträge, Renten- und Steuerunterlagen — alles aufbewahren, bis Steuerangelegenheiten geregelt sind.",
      "Erinnerungsstücke: Fotos, Briefe, Schmuck, Schreibutensilien — was an Familie, Freunde oder Sie persönlich gehen soll.",
      "Wertgegenstände: Schmuck, Münzen, Briefmarken, Antiquitäten, Kunstwerke — vor der Räumung dokumentieren (Fotos), ggf. von einem Auktionator schätzen lassen.",
      "Digital: Smartphones, PCs — Datenschutz beachten, Festplatten ggf. löschen oder physisch zerstören.",
      "Schlüssel zu Schließfächern oder Tresoren — separat verwahren.",
    ] },
    { type: "h2", text: "Schritt 5 — Entrümpelungsfirma beauftragen" },
    { type: "p", text: "Wenn die persönlichen Dinge sortiert sind, kann der Profi kommen. Worauf bei der Auswahl achten:" },
    { type: "ol", items: [
      "Festpreis nach Besichtigung — keine Stundenabrechnung mit offenem Ende.",
      "Eigene Mitarbeiter, keine Subunternehmer.",
      "Betriebshaftpflicht nachgewiesen.",
      "Einfühlsames Vorgehen — bei Bedarf Ruhepausen, Möglichkeit der Anwesenheit.",
      "Auf Wunsch besenreine Endreinigung für die Wohnungsübergabe.",
      "Schriftliche Auftragsbestätigung mit Datum, Umfang, Preis.",
    ] },
    { type: "h2", text: "Schritt 6 — Steuerliche Aspekte" },
    { type: "p", text: "Erbschaftssteuer: Freibetrag für Kinder 400 000 €, Ehegatten 500 000 €, Eltern 100 000 €, Geschwister/Nichten/Neffen 20 000 €. Bei Überschreitung Anzeige beim Finanzamt binnen 3 Monaten. Bei Wohnungsverkauf später: Spekulationssteuer prüfen (10-Jahres-Frist)." },
    { type: "h2", text: "Schritt 7 — Wohnungsübergabe" },
    { type: "p", text: "Vermieter erwartet meist „besenreine“ Übergabe: Räume sind leer, gefegt, von gröberem Schmutz befreit. Größere Reparaturen (Renovierung, Bohrlöcher schließen) hängen vom Mietvertrag ab. Übergabeprotokoll mit Foto-Dokumentation der Räume, Zählerständen und Schlüsselzahl." },
    { type: "h2", text: "Emotionale Aspekte" },
    { type: "p", text: "Es ist normal, wenn die Räumung Sie emotional fordert. Tipps aus der Praxis:" },
    { type: "list", items: [
      "Nehmen Sie sich Zeit. Eine Wohnung muss nicht in 3 Tagen geräumt sein. 2-4 Wochen sind realistisch.",
      "Bringen Sie eine Vertrauensperson mit, wenn Sie selbst die Wohnung durchgehen.",
      "Pausen einplanen — nicht alles auf einen Tag.",
      "Was Sie heute nicht entscheiden können, packen Sie in eine Kiste „Später“. In 6 Monaten sehen die Dinge oft anders aus.",
      "Foto-Dokumentation der Wohnung vor der Räumung — viele finden das hilfreich für die Erinnerung.",
    ] },
    { type: "h2", text: "Was bei uns anders läuft" },
    { type: "p", text: "Bei Haushaltsauflösungen nach Todesfall im Raum Osnabrück gehen wir bewusst behutsam vor. Das beginnt mit einer ruhigen Besichtigung — Sie zeigen uns die Wohnung in Ihrem Tempo, wir erfassen den Umfang und beantworten Ihre Fragen. Anschließend erhalten Sie ein Festpreisangebot. Wertgegenstände werden nicht angerechnet — was Sie behalten oder selbst verwerten möchten, lassen wir stehen. Persönliche Dokumente, die wir bei der Räumung finden, übergeben wir Ihnen separat." },
    { type: "h2", text: "Erbrecht-Grundlagen kompakt — was Sie wissen müssen" },
    { type: "p", text: "Bei einem Todesfall ohne Testament gilt die gesetzliche Erbfolge. Erste Ordnung: Kinder und Enkel. Zweite: Eltern und Geschwister. Dritte: Großeltern und ihre Nachfahren. Ehegatten erben neben Verwandten — bei Zugewinngemeinschaft (gesetzlicher Güterstand): 1/2 neben Kindern, 3/4 neben Eltern oder Geschwistern. Lebensgefährten erben nur mit Testament — nichts ohne." },
    { type: "p", text: "Falls ein Testament existiert, wird es nach dem Todesfall beim Nachlassgericht eröffnet. In Osnabrück: Amtsgericht Osnabrück, Kollegienwall 7. Erbschein: bei reiner gesetzlicher Erbfolge meist erforderlich, Antrag beim Notar oder direkt beim Nachlassgericht. Gebühr richtet sich nach dem Nachlasswert (z.B. bei 100 000 € Nachlasswert: ca. 273 € Gebühr)." },
    { type: "h2", text: "Wertgegenstände und Erbschaftsteuer" },
    { type: "p", text: "Erbschaftsteuer-Freibeträge ab 2026 (Stand bei Drucklegung):" },
    { type: "list", items: [
      "Ehepartner: 500 000 €",
      "Kinder: je 400 000 € (pro Kind)",
      "Enkel: je 200 000 €",
      "Eltern (bei Erbschaft von Kind): 100 000 €",
      "Geschwister, Nichten/Neffen: je 20 000 €",
      "Andere Personen (z.B. Lebensgefährten ohne Heirat): 20 000 €",
    ] },
    { type: "p", text: "Wenn der Wert des Nachlasses unter dem Freibetrag liegt, fällt keine Erbschaftsteuer an — und Sie müssen nichts beim Finanzamt anzeigen (auch wenn manche das vorsorglich tun). Bei Überschreitung: Anzeigepflicht innerhalb von 3 Monaten beim zuständigen Finanzamt. In Osnabrück: Finanzamt Osnabrück-Stadt für Stadt OS, Finanzamt Osnabrück-Land für Landkreise. Selbständig steuerlich beraten lassen, wenn Wertgegenstände dabei sind." },
    { type: "h2", text: "Psychologische Aspekte — Trauer und Aufgaben gleichzeitig" },
    { type: "p", text: "Eine Haushaltsauflösung im Todesfall ist nicht primär eine technische Aufgabe — sie ist auch ein Trauer-Schritt. Es ist normal, wenn die Aufgabe Sie überfordert: Persönliche Erinnerungen, ungelöste Beziehungskonflikte, Schuldgefühle beim Wegwerfen, Erschöpfung von der Bestattungsorganisation. Tipps aus der Praxis:" },
    { type: "list", items: [
      "Nehmen Sie sich 2-4 Wochen Zeit. Es muss nicht in 3 Tagen erledigt sein.",
      "Bringen Sie eine Vertrauensperson mit, wenn Sie zum ersten Mal die Wohnung betreten.",
      "Was Sie heute nicht entscheiden können, packen Sie in eine Kiste „später“. Nach 6 Monaten sehen die Dinge oft anders aus.",
      "Foto-Dokumentation der Wohnung vor der Räumung — viele finden das hilfreich für die spätere Erinnerung.",
      "Beratungsangebote bei der Caritas, Diakonie und Trauergruppen in Osnabrück, Bramsche, Melle nutzen — kostenlos und niedrigschwellig.",
      "Bei Überforderung: einen Hausmeisterservice oder Bestattungsunternehmen mit erweitertem Service beauftragen, der die Wohnungsabwicklung mitübernimmt.",
    ] },
    { type: "p", text: "Wir kennen diese Situation und nehmen uns Zeit. Wenn Sie nicht selbst dabei sein möchten, übernehmen wir auch die komplette Auflösung mit anschließender Schlüsselübergabe an die Hausverwaltung — Sie hören dann nur einmal von uns mit der Bestätigung „erledigt“." },
    { type: "callout", text: "Eine kostenlose Besichtigung im 60-km-Umkreis um Osnabrück — wir nehmen uns Zeit. Tel: +49 1523 9603175 oder kontakt@rundumshaus-littawe.de." },
  ],

  // ════════════════════════════════════════════════════════════════
  "winterdienst-pflichten-vermieter-eigentuemer": [
    { type: "p", text: "Sobald die ersten Schneeflocken in Osnabrück, Bramsche oder Münster fallen, beginnt für Eigentümer und Vermieter eine rechtlich heikle Phase: die Winterdienstpflicht. Wer sie verletzt, riskiert Schadensersatz im fünfstelligen Bereich, wenn ein Passant auf glatter Stelle stürzt. Dieser Guide erklärt, wer was wann tun muss — speziell für Niedersachsen und Nordrhein-Westfalen." },
    { type: "h2", text: "Wer ist verantwortlich?" },
    { type: "h3", text: "Grundsatz" },
    { type: "p", text: "Die Verkehrssicherungspflicht für Gehwege liegt grundsätzlich bei der Gemeinde. Per kommunaler Satzung wird sie in praktisch allen Städten in NDS/NRW auf die Anlieger — also Grundstückseigentümer — übertragen. In Osnabrück ist das in der „Straßenreinigungssatzung der Stadt Osnabrück“ geregelt; ähnliche Satzungen gelten in Bramsche, Melle, Bielefeld und allen anderen 94 Städten unseres Einsatzgebiets." },
    { type: "h3", text: "Übertragung an Mieter" },
    { type: "p", text: "Vermieter können die Streupflicht per Mietvertrag oder Hausordnung auf Mieter übertragen. Wirksam ist das nur, wenn:" },
    { type: "list", items: [
      "Es ausdrücklich im Mietvertrag oder einer einbezogenen Hausordnung steht.",
      "Klare Regeln existieren (welcher Mieter wann verantwortlich ist — Klingelschild-Reihenfolge etc.).",
      "Streumittel und Werkzeug zur Verfügung stehen.",
      "Der Vermieter die Einhaltung kontrolliert (nicht regelmäßig vor Ort: Übertragung kann unwirksam werden).",
    ] },
    { type: "p", text: "Auch nach Übertragung bleibt der Vermieter mit Kontrollpflicht eingebunden. Bei Mehrfamilienhäusern empfiehlt sich die Beauftragung eines Hausmeisterservice — verlässlicher und rechtssicherer als die Übertragung an Mieter." },
    { type: "h2", text: "Räum- und Streuzeiten" },
    { type: "list", items: [
      "Werktags ab 7:00 Uhr: Gehwege müssen begehbar sein.",
      "Sonn- und Feiertags ab 9:00 Uhr.",
      "Bis abends 20:00 Uhr (in einigen Gemeinden 22:00 Uhr) durchgehend zu kontrollieren und ggf. nachzustreuen.",
      "Bei Schneefall am Tag: regelmäßiges Nachräumen — als Faustregel alle 1-2 Stunden bei kontinuierlichem Schneefall.",
    ] },
    { type: "p", text: "In den meisten Satzungen in NDS/NRW gilt die Pflicht für Gehwege auf einer Breite von 1,00–1,50 m. Die genaue Breite hängt von der kommunalen Satzung ab — in Osnabrück 1,20 m, in Bielefeld 1,00 m." },
    { type: "h2", text: "Was darf wie gestreut werden?" },
    { type: "p", text: "Streumittel sind nicht überall gleich erlaubt. In NDS/NRW gilt typisch:" },
    { type: "list", items: [
      "Erlaubt: Sand, Granulat (Splitt), Sägespäne, abstumpfende Mittel.",
      "Eingeschränkt erlaubt: Salz nur bei extremer Glätte (Eisregen) oder an gefährlichen Stellen (Treppen, Steigungen).",
      "Verboten in vielen Gemeinden: flächendeckendes Salzstreuen — ökologische Gründe (Salzbelastung von Bäumen und Boden).",
    ] },
    { type: "p", text: "In Osnabrück und großen Teilen des Landkreises sowie im Münsterland gilt seit 2019 ein Salzstreuverbot in Wohngebieten. Salz darf nur an gefährlichen Stellen (Steigungen, Treppen) eingesetzt werden. Bei Verstößen drohen Bußgelder bis 1 000 €." },
    { type: "h2", text: "Was passiert bei Pflichtverletzung?" },
    { type: "p", text: "Stürzt jemand auf nicht geräumtem oder nicht gestreutem Gehweg, kann er Schadensersatz und Schmerzensgeld verlangen. Die Höhe richtet sich nach Verletzungsgrad:" },
    { type: "list", items: [
      "Prellung, Hämatom: 200–800 € Schmerzensgeld.",
      "Knochenbruch: 2 000–8 000 €.",
      "Bandscheibenvorfall: 5 000–15 000 €.",
      "Bleibende Schäden: über 30 000 €.",
      "Plus Schadensersatz für Verdienstausfall, Krankenhaus, Reha.",
    ] },
    { type: "p", text: "Eine private Haftpflichtversicherung deckt das in der Regel ab — vorausgesetzt, Sie haben keine grobe Fahrlässigkeit begangen (z.B. mehrere Tage gar nicht geräumt). Hausverwaltungen sollten eine zusätzliche Verkehrssicherungs-Haftpflicht abschließen." },
    { type: "h2", text: "Was kostet ein professioneller Winterdienst?" },
    { type: "p", text: "Für ein Einfamilienhaus mit Gehweg und Hofzufahrt typische Saison-Pauschalen 2026 in der Region Osnabrück:" },
    { type: "list", items: [
      "Einsatz nur bei Bedarf, abrufbasiert: 30–45 € pro Einsatz, in einer Saison meist 8-15 Einsätze (= 250–650 €).",
      "Saison-Pauschale Nov–März für Standardgehweg: 200–400 €.",
      "Mehrfamilienhaus mit Treppenhaus, Gehweg und Hofzufahrt: 350–700 € Saison-Pauschale.",
      "Inklusive Streumittel oder gegen Aufpreis (Sand: 30–60 € Saison).",
    ] },
    { type: "h2", text: "Wann sich der Profi lohnt" },
    { type: "list", items: [
      "Vermieter mit Mehrfamilienhaus — rechtssicherer als Übertragung auf Mieter.",
      "Berufstätige, die zwischen 6:30 und 7:00 Uhr nicht zuverlässig vor Ort sein können.",
      "Wer mehrere Wohnungen oder Häuser besitzt.",
      "Bei Personen mit gesundheitlichen Einschränkungen (Schneeschippen ist Schwerstarbeit, Herzinfarkt-Risiko).",
      "Bei längeren Abwesenheiten (Urlaub) — die Streupflicht ruht nicht.",
    ] },
    { type: "h2", text: "Hausmeisterservice mit Winterdienst — wie unsere Verträge laufen" },
    { type: "p", text: "Wir bieten in Osnabrück und im 60-km-Umkreis Winterdienst-Verträge in zwei Varianten an: abrufbasiert (Sie rufen an, wir kommen) oder Saison-Pauschale (wir prüfen täglich, kommen automatisch wenn nötig). Für Mehrfamilienhäuser empfehlen wir die Pauschale — sie ist rechtlich sicherer, weil die Kontrolle dokumentiert wird." },
    { type: "h2", text: "Beispiel-Mietvertragsklausel zur Übertragung der Streupflicht" },
    { type: "p", text: "Wenn Sie als Vermieter die Streupflicht auf Mieter übertragen möchten, muss das schriftlich, klar und mit Werkzeug-Stellung verbunden sein. Beispiel-Klausel, die in den meisten Bundesländern (auch NDS und NRW) wirksam ist:" },
    { type: "quote", text: "„Der Mieter übernimmt für den nach kommunaler Satzung dem Vermieter obliegenden Winterdienst (Räum- und Streupflicht) im Bereich des Gehwegs vor dem Haus. Der Winterdienst ist werktags ab 7:00 Uhr, sonn- und feiertags ab 9:00 Uhr bis 20:00 Uhr durchzuführen. Der Vermieter stellt Schaufel, Besen und Streumittel zur Verfügung. Bei mehreren Mietparteien wird ein Räumplan an der Hausordnung ausgehängt.“" },
    { type: "p", text: "Wichtig: Diese Klausel allein reicht nicht. Sie als Vermieter müssen die Einhaltung kontrollieren — bei Pflichtverletzungen durch Mieter haften Sie als Eigentümer mit. Bei wiederholten Verstößen sollten Sie schriftlich abmahnen. Bei mehrfachen Mietern in einem Haus empfiehlt sich ein Räumplan mit klaren Verantwortlichkeiten — sonst entsteht Streit, wer „heute dran ist“." },
    { type: "h2", text: "Streumittel-Vergleich für die Region" },
    { type: "list", items: [
      "Sand (Strandsand, gewaschen): umweltfreundlich, abstumpfend, keine Boden- oder Pflanzenschäden. Nachteil: schwere Reinigung im Frühling, sammelt sich in Gullys.",
      "Granitsplitt: ähnlich Sand, etwas wirksamer auf glattem Eis. Wiederverwertbar (im Frühjahr aufkehren).",
      "Lavagranulat: leicht (rückenschonend), umweltfreundlich, etwas teurer.",
      "Sägespäne: traditionelles Hausmittel, wirkt abstumpfend, biologisch abbaubar. Bei Regen schmierig.",
      "Salz (NaCl, Streusalz): in Osnabrück und vielen NDS/NRW-Gemeinden in Wohngebieten verboten. Nur bei extremer Eisbildung an Treppen und Steigungen erlaubt. Schadet Bäumen und Boden, fördert Korrosion an Metall.",
      "Salz-Solemix (Sole): sparsamer als reines Salz, aber gleiche Umweltprobleme. Nur professioneller Einsatz auf Hauptstraßen sinnvoll.",
    ] },
    { type: "p", text: "Empfehlung für Privateigentümer und Hausverwaltungen: Sand oder Granitsplitt als Standard. Salz nur als Notfall-Reserve für extreme Glätte an gefährlichen Stellen (Treppen, steile Auffahrten). Im Landkreis Osnabrück gilt seit 2019 ein Salzstreuverbot in Wohngebieten — bei Verstoß Bußgeld bis 1 000 €." },
    { type: "h2", text: "Was tun bei tatsächlichem Sturzfall?" },
    { type: "p", text: "Stürzt jemand auf Ihrem Gehweg, ist der Ablauf rechtlich klar:" },
    { type: "ol", items: [
      "Erste Hilfe leisten (auch als Eigentümer/Mieter Pflicht).",
      "Notruf 112 bei sichtbaren Verletzungen.",
      "Sofort dokumentieren: Foto-Dokumentation des Gehwegs, Wettersituation, Glättegrad. Zeugen-Kontakte sammeln.",
      "Eigene Haftpflichtversicherung informieren — Streupflicht-Verstöße sind dort meist mitversichert. Schadensmeldung schriftlich.",
      "Mit dem Verletzten gerne im Kontakt bleiben — eine entgegenkommende Haltung mindert oft Schadenshöhen.",
      "Nicht: Schuld vorab schriftlich anerkennen oder ohne Versicherung Vergleiche schließen.",
    ] },
    { type: "p", text: "Wichtig zu wissen: Bei einem nachgewiesenen Sturz auf nicht geräumten Gehweg sind Schmerzensgelder von 5 000 € bei Knochenbrüchen, 15 000 € bei Bandscheibenvorfällen, über 30 000 € bei dauerhaften Schäden realistisch. Plus Schadensersatz für Verdienstausfall, Krankenhaus, Reha. Diese Beträge übernimmt die private Haftpflicht meist — vorausgesetzt, Sie haben nicht grob fahrlässig gehandelt (z.B. mehrere Tage gar nicht geräumt)." },
    { type: "callout", text: "Winterdienst-Vertrag für Saison Nov 2026 – März 2027 jetzt anfragen. Kostenlose Besichtigung im 60-km-Umkreis um Osnabrück. +49 1523 9603175." },
  ],

  // ════════════════════════════════════════════════════════════════
  "gaertner-vs-selbst-machen-wann-lohnt": [
    { type: "p", text: "„Gärtnern macht doch Spaß — warum jemanden bezahlen?“ Das hört man oft, und in vielen Fällen ist es richtig. In manchen aber nicht. Diese Analyse hilft Ihnen, eine sachliche Entscheidung zu treffen: Wann lohnt sich der Profi-Gärtner in der Region Osnabrück, und wann ist Eigenleistung die bessere Wahl?" },
    { type: "h2", text: "Die ehrliche Stundenlohn-Rechnung" },
    { type: "p", text: "Gärtner-Stundenlohn in NDS/NRW 2026: 30–45 € netto. Eigenleistung: kostenfrei — vermeintlich. Tatsächlich hat Ihre Zeit einen Wert. Wenn Sie selbst 35 € pro Stunde verdienen (Bruttogehalt geteilt durch 1 700 Jahresstunden), dann kostet Sie eine Stunde im Garten dasselbe wie der Profi. Mit dem Unterschied, dass der Profi schneller ist." },
    { type: "h2", text: "Geschwindigkeitsfaktor — wo der Profi 2-3× schneller ist" },
    { type: "list", items: [
      "Heckenschnitt 30 m, 1,80 m hoch: Sie 4-6 h, Profi 1,5-2 h.",
      "Vertikutieren 200 m² Rasen: Sie 3-4 h, Profi 1-1,5 h.",
      "Rasensanierung mit Düngung und Nachsaat: Sie 5-7 h, Profi 2-3 h.",
      "Frühjahrsschnitt eines mittleren Gartens: Sie 8-12 h, Profi 3-5 h.",
      "Heckenneuanlage 10 m: Sie 6-8 h, Profi 2-3 h.",
    ] },
    { type: "p", text: "Der Profi ist schneller wegen Erfahrung, Profi-Werkzeug und Routine. Kein Rasenmäher-Schubsen mit Rückenschmerzen, sondern Aufsitzmäher oder Großflächenmäher." },
    { type: "h2", text: "Wann sich Eigenleistung lohnt" },
    { type: "list", items: [
      "Kleiner Stadtgarten in Osnabrück (bis 200 m²) ohne komplexe Bepflanzung.",
      "Sie haben Spaß und Zeit am Wochenende — Garten als Hobby.",
      "Werkzeug ist vorhanden (gekauft oder geliehen vom Nachbarn).",
      "Keine körperlichen Einschränkungen (Rücken, Knie, Herz).",
      "Heckenhöhe unter 1,80 m — keine Leiterarbeit nötig.",
    ] },
    { type: "h2", text: "Wann sich der Profi lohnt" },
    { type: "list", items: [
      "Garten über 500 m² — der Zeitaufwand explodiert.",
      "Hecken über 2 m Höhe — Leiterarbeit ist gefährlich, Hubsteiger nötig.",
      "Berufliche Hochlast oder lange Pendelwege.",
      "Körperliche Einschränkungen, höheres Alter.",
      "Spezialaufgaben: Rasenneuanlage, Vertikutieren, Baumpflege, Heckenrückschnitt im Oktober/November (oft ein einzelner schwerer Arbeitstag).",
      "Außenanlagen von Mehrfamilienhäusern — Pflege durch Eigentümergemeinschaft scheitert oft an Koordination.",
    ] },
    { type: "h2", text: "Beispielrechnung: Garten 400 m² in Bramsche" },
    { type: "p", text: "Standardgarten mit Rasen 200 m², Hecke 25 m (1,80 m hoch), 30 m² Beete, einer Apfelbaum-Gruppe." },
    { type: "h3", text: "Eigenleistung pro Jahr" },
    { type: "list", items: [
      "Rasenmähen 25× pro Saison: 25 × 1 h = 25 h.",
      "Vertikutieren + Düngen 2× pro Jahr: 6 h.",
      "Heckenschnitt 2× pro Jahr: 2 × 4 h = 8 h.",
      "Beetpflege monatlich: 12 × 2 h = 24 h.",
      "Apfelbaumpflege: 4 h.",
      "Laubentfernung im Herbst: 10 h.",
      "Werkzeug warten: 4 h.",
      "Summe: 81 h pro Jahr. Plus Werkzeug-Anschaffung/Wartung ca. 200 € pro Jahr.",
    ] },
    { type: "p", text: "Bei einer Eigenstunde von 35 € entspricht das einem Wert von 81 × 35 = 2 835 €. Plus 200 € Material — 3 035 € pro Jahr." },
    { type: "h3", text: "Profi-Gartenpflege für gleiches Programm in Bramsche" },
    { type: "list", items: [
      "Wöchentliches Mähen, ca. 25× × 30 min × 35 €/h = 437 €.",
      "Vertikutieren + Düngen: 200 €.",
      "Heckenschnitt: 2 × 200 € = 400 €.",
      "Beetpflege monatlich (1 h): 12 × 35 € = 420 €.",
      "Apfelbaumpflege: 100 €.",
      "Laubentfernung: 250 €.",
      "Summe: ca. 1 800–2 200 € pro Jahr inkl. Anfahrt und Entsorgung.",
    ] },
    { type: "p", text: "Erkenntnis: Bei monetärer Bewertung der Eigenzeit ist der Profi günstiger — vorausgesetzt, Sie würden in der Zeit tatsächlich Geld verdienen. Wer Garten als Hobby liebt, rechnet anders." },
    { type: "h2", text: "Der Mittelweg: Saisonale Aufträge an den Profi" },
    { type: "p", text: "Viele Gartenbesitzer in Osnabrück und Umgebung wählen den Mittelweg: Mähen und kleine Beetpflege selbst, große oder körperlich anstrengende Arbeiten an den Profi:" },
    { type: "list", items: [
      "Heckenschnitt 2× pro Jahr (Juni + August).",
      "Vertikutieren und Düngen im Frühjahr.",
      "Großer Rückschnitt im November.",
      "Laubentfernung im Herbst.",
    ] },
    { type: "p", text: "Kosten für Mittelweg: 600–1 000 € pro Jahr. Sie sparen die körperlich härtesten Arbeiten und behalten den Garten als Hobby." },
    { type: "h2", text: "Was beim Profi wichtig ist" },
    { type: "ol", items: [
      "Festpreis nach Besichtigung — keine Überraschungen.",
      "Eigenes Werkzeug — keine versteckten „Werkzeugkosten“.",
      "Schnittgut-Entsorgung enthalten.",
      "Versicherung (Betriebshaftpflicht) nachgewiesen.",
      "Bewertung von Bestandskunden — bei lokalen Anbietern oft auf Google Maps oder über Kollegen erfragbar.",
    ] },
    { type: "h2", text: "Werkzeug-Anschaffung versus Mieten" },
    { type: "p", text: "Wer überlegt, in eigenes Garten-Werkzeug zu investieren, sollte rechnen. Typische Anschaffungskosten 2026:" },
    { type: "list", items: [
      "Akku-Rasenmäher (mittlere Klasse): 350-600 €, Lebensdauer 7-10 Jahre.",
      "Akku-Heckenschere: 80-300 €, Lebensdauer 5-8 Jahre.",
      "Vertikutierer (elektrisch): 150-300 €, Lebensdauer 5-10 Jahre.",
      "Astschere und manuelle Werkzeuge: 50-150 € insgesamt, Lebensdauer 10-20 Jahre.",
      "Aufbewahrung Schuppen oder Garage: vorhanden oder Anschaffungskosten.",
      "Wartung pro Jahr: ca. 10-15 % der Anschaffungskosten (Schmieröl, Klingenwechsel, Akkus).",
    ] },
    { type: "p", text: "Alternative: Werkzeug mieten. In Osnabrück und Umgebung gibt es zahlreiche Baumärkte (Hornbach, Obi, Bauhaus) und Werkzeugverleih, die Vertikutierer für 25-40 € pro Tag, Akku-Heckenscheren für 15-25 €, Hubsteiger für 80-150 € am Tag verleihen. Wer einmal pro Jahr einen großen Auftrag hat — Vertikutieren, Heckenschnitt am Hochsommer-Wochenende — fährt mit Mieten oft besser. Eigenwerkzeug lohnt sich erst bei regelmäßigem Einsatz." },
    { type: "h2", text: "Saisonale Preise — wann ist Profi-Auslastung niedrig?" },
    { type: "p", text: "Profi-Anbieter in der Region Osnabrück haben saisonale Schwankungen — und das beeinflusst die Preise. Hauptsaison (April-Oktober): hohe Auslastung, Preise stabil bis leicht erhöht, Wartezeiten 1-3 Wochen. Nebensaison (November-März, ohne Winterdienst): freie Kapazitäten, oft Sonderkonditionen für große Aufträge wie Heckenrückschnitt vor dem 1. März, Gartenneuanlage, Bodenarbeiten." },
    { type: "p", text: "Mein Tipp: Wenn Sie eine Hecke radikal zurückschneiden, Bäume fällen oder Ihren Garten umgestalten möchten — beauftragen Sie das im Februar oder Anfang März. Sie bekommen schnellere Termine und oft 10-15 % günstigere Preise als im Mai/Juni." },
    { type: "h2", text: "Fall-Studie: Familie K. aus Bramsche, 800 m² Garten" },
    { type: "p", text: "Familie K. hat ein Reihenhaus in Bramsche mit 800 m² Garten — Rasen 400 m², Hecke 35 m, Beete, ein Apfelbaum. Beide Eltern berufstätig, 2 Kinder. Variante „alles selbst“: 95 Stunden pro Jahr, gefühlte Belastung „immer aktuell“. Variante „nur Profi“: ca. 2 200 € pro Jahr, kein Aufwand, aber kein Hobby-Garten-Erlebnis. Mittelweg-Variante (ihre Wahl): wöchentliches Mähen + leichte Beetpflege selbst (40 Std/Jahr), Heckenschnitt 2× pro Jahr Profi (400 €), Frühjahrspflege Profi (200 €), Laubentfernung Herbst Profi (180 €), Apfelbaumpflege Profi (100 €) = 880 € Profi-Anteil + 40 Std Eigenleistung. Ergebnis: Garten bleibt gepflegt, Familie hat noch Garten-Erlebnis ohne Überforderung." },
    { type: "callout", text: "Mittelweg-Verträge oder einzelne Saisonaufträge im 60-km-Umkreis um Osnabrück. Kostenlose Besichtigung. +49 1523 9603175." },
  ],

  // ════════════════════════════════════════════════════════════════
  "garten-anlegen-kosten-2026": [
    { type: "p", text: "Wer in Osnabrück, Bramsche oder Münster einen neuen Garten anlegen möchte — sei es nach einem Hauskauf, einer Modernisierung oder als komplette Neugestaltung —, steht vor einer komplexen Kostenfrage. Die Spanne reicht von 30 € pro Quadratmeter (einfache Rasenfläche) bis 350 € pro Quadratmeter (vollwertige Gartenanlage mit Pflasterung, Beeten und Hecke). Dieser Guide bringt Struktur in die Kalkulation." },
    { type: "h2", text: "Die fünf Kostenfaktoren" },
    { type: "h3", text: "1. Größe der Fläche" },
    { type: "p", text: "Quadratmeterpreis sinkt mit zunehmender Fläche — bis zu einem gewissen Punkt. Bei sehr großen Flächen kommen Maschinenkosten und Logistik dazu. Im Bereich 100-500 m² liegt der wirtschaftliche Sweet Spot." },
    { type: "h3", text: "2. Bodenverhältnisse" },
    { type: "p", text: "Im Osnabrücker Land herrschen verbreitet sandige Lehm- und Lehmböden, im Münsterland eher tonige Böden. Beide eignen sich nach Bearbeitung. Spezialfälle: Moorböden im Hahnenmoor oder bei Diepholz erfordern Drainage; sehr kiesige Böden auf Hügellagen erfordern Mutterboden-Auftrag (35–55 € pro m³, 0,2-0,3 m³ pro m² Fläche)." },
    { type: "h3", text: "3. Bestandselemente" },
    { type: "p", text: "Komplette Neuanlage auf Brache (z.B. nach Hausneubau): am teuersten. Renovierung eines bestehenden, vernachlässigten Gartens: günstiger, weil oft Bestandsbäume und Strukturen erhalten werden können. Pflasterabbau alter Wege: 25-40 € pro m²." },
    { type: "h3", text: "4. Auswahl der Pflanzen" },
    { type: "p", text: "Standard-Liguster-Hecke: 8-15 € pro laufendem Meter (Pflanzen + Pflanzung). Premium-Hecke (Kirschlorbeer, Buchsbaum): 25-50 € pro lfm. Stauden 5-15 € pro Stück, gepflanzt. Sträucher 25-100 € je nach Größe. Bäume 80-500 €." },
    { type: "h3", text: "5. Wege, Pflasterungen, Pergola, Teich" },
    { type: "p", text: "Pflasterweg 1 m breit: 100-180 € pro lfm inkl. Untergrund. Terrasse 30 m²: 4 500-9 000 €. Pergola Holz 4 × 3 m: 2 000-4 500 €. Gartenteich 10 m²: 2 500-7 000 €." },
    { type: "h2", text: "Beispielrechnungen" },
    { type: "h3", text: "Beispiel 1: Standardgarten 200 m² in Belm" },
    { type: "p", text: "Reine Rasenfläche mit Hecke und einfachen Beeten." },
    { type: "list", items: [
      "Bodenvorbereitung (Lockern, Mutterboden, Planieren): 1 500 €.",
      "Rasen 150 m² (Saat oder Rollrasen): 700-1 800 €.",
      "Hecke 20 m Liguster: 200 €.",
      "Beete 30 m² mit Stauden: 600-1 200 €.",
      "Schmaler Plattenweg 8 m: 800 €.",
      "Summe: 3 800-5 500 €.",
    ] },
    { type: "h3", text: "Beispiel 2: Mittlerer Garten 400 m² in Melle" },
    { type: "p", text: "Mit Terrasse, Beeten, Hecke, größerer Pflasterung." },
    { type: "list", items: [
      "Bodenvorbereitung: 3 000 €.",
      "Rasen 250 m²: 1 200-3 000 €.",
      "Hecke 40 m Premium (Hainbuche): 800 €.",
      "Beete 80 m²: 1 500-3 000 €.",
      "Terrasse 25 m² gepflastert: 4 000 €.",
      "Wege und Beeteinfassungen: 1 500 €.",
      "Drei Sträucher und zwei Bäume: 800-1 500 €.",
      "Summe: 12 800-16 800 €.",
    ] },
    { type: "h3", text: "Beispiel 3: Premiumgarten 600 m² in Bielefeld" },
    { type: "p", text: "Vollausstattung mit Pergola, Teich, Beleuchtung, automatischer Bewässerung." },
    { type: "list", items: [
      "Bodenvorbereitung mit Drainage: 4 500 €.",
      "Rasen 300 m² Rollrasen: 3 600 €.",
      "Hecke 50 m Kirschlorbeer + Eibe: 2 500 €.",
      "Beete 120 m² mit aufwendiger Bepflanzung: 4 500 €.",
      "Terrasse 40 m² Naturstein: 8 000 €.",
      "Pergola 4 × 3 m: 4 000 €.",
      "Gartenteich 8 m²: 5 000 €.",
      "Wege Naturstein: 3 500 €.",
      "Beleuchtung LED-System: 2 500 €.",
      "Bewässerungsanlage: 3 000 €.",
      "Bäume und Sträucher: 3 000 €.",
      "Summe: 44 000 €.",
    ] },
    { type: "h2", text: "Was Sie selbst übernehmen können" },
    { type: "p", text: "Spareffekte durch Eigenleistung sind hoch — wenn Sie Zeit haben:" },
    { type: "list", items: [
      "Pflanzungen (Stauden, einfache Hecken): 30-40 % Ersparnis.",
      "Rasensaat statt Rollrasen: 50 % Ersparnis bei mehr Geduld.",
      "Beeteinfassungen aus Stahlbändern selbst gesetzt: 50 % Ersparnis.",
      "Hilfsdienste beim Pflasterabbau: 30 % Ersparnis.",
    ] },
    { type: "p", text: "Nicht selbst machen sollten Sie: Drainage (Fachwissen nötig), Pflasterungen mit größerem Untergrund (Fundament setzt sich falsch), Elektroinstallationen, Großpflanzungen (Bäume) — Risikoarbeiten." },
    { type: "h2", text: "Förderungen prüfen" },
    { type: "p", text: "Einige Kommunen in NDS/NRW fördern naturnahe Gartenanlagen, Versickerungsflächen statt Pflasterung oder Dachbegrünung. In Osnabrück gibt es das Programm „Grüne Hauptstadt“-Förderung für naturnahe Gärten — Zuschüsse 250-2 000 € je nach Maßnahme. In Bielefeld und Münster ähnliche Programme. Vor dem Bau bei der Stadt anfragen." },
    { type: "h2", text: "Genehmigungspflichten" },
    { type: "list", items: [
      "Reine Gartenanlage: keine Genehmigung.",
      "Größere Pflasterung über 50 m²: in einigen Gemeinden Niederschlagswasser-Anzeige.",
      "Bäume über 1,5 m Wuchshöhe in Vorgärten: kommunale Baumschutzsatzung prüfen (in Osnabrück Bäume ab 80 cm Stammumfang geschützt).",
      "Dachbegrünung von Carport oder Schuppen: ggf. Bauantrag.",
      "Tiefer Teich (>1 m): in NDS/NRW oft anzeigepflichtig.",
    ] },
    { type: "h2", text: "Ablauf einer Gartenneuanlage" },
    { type: "ol", items: [
      "Erstgespräch und kostenlose Besichtigung — Erfassung von Wünschen, Bestand, Vorstellungen.",
      "Grobplan mit ungefährer Kostenschätzung.",
      "Detailplanung mit verbindlichem Festpreis nach finaler Abstimmung.",
      "Ausführung — je nach Umfang 1-6 Wochen.",
      "Abnahme mit Übergabe-Protokoll und Pflegehinweisen.",
      "Auf Wunsch: Folgevertrag für laufende Gartenpflege.",
    ] },
    { type: "callout", text: "Kostenlose Besichtigung im 60-km-Umkreis um Osnabrück. Wir besprechen Ihre Wünsche und kalkulieren den passenden Umfang. +49 1523 9603175." },
  ],
};
